### ISSUE TITLE
add a reset button to builds

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#10]
<a href="https://github.com/bacongobbler"><img src="https://avatars2.githubusercontent.com/u/1360539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bacongobbler](https://github.com/bacongobbler)**
_2017-07-07 15:49:25_

----

I need a nice pretty "reset" button to re-jigger failed/flaky builds.

**Comment by bacongobbler** [comment]
**Comment by [technosophos](https://github.com/technosophos)**
_2017-07-07 20:57:48_

----

Until we get this added, you can do the one in GitHub's settings->webhooks

**Comment by technosophos** [comment]
Quietly closing this, since it refers to a different project. ;-)
