### ISSUE TITLE
Group.runEach only returns result for last job

### ISSUE THREAD

**Issue by mazzus** [Azure/brigade#100]
Group.runEach only returns the result for the last job. 
It would be great to get the result for every job which was run. Group.runAll, for example, returns the results of all the jobs. Something like Bluebird Promise's each() -function would be nice!

**Comment by technosophos** [comment]
That seems reasonable. The code in question is here: https://github.com/Azure/brigade/blob/master/brigade-worker/src/group.ts#L56-L60

It was a really basic first-pass, so it should be fairly straightforward to modify.
