### ISSUE TITLE
Consistent failure to handle pull_request events

### ISSUE THREAD

**Issue by j2sol** [Azure/brigade#111]
I've got a working setup that is handling push events just fine, however when I try to handle a pull_request event, my job always fails with a `(rejection)`.

https://github.com/j2sol/demobrigade/blob/master/brigade.js  is a link to the brigade script.

The log looks like
```
> kubectl logs brigade-worker-01by9z7cq5wywp41nqmsph1pv0-25bf7990
yarn run v1.1.0
$ node prestart.js
prestart: src/brigade.js written
$ node --no-deprecation ./dist/src/index.js
Creating PVC named brigade-worker-01by9z7cq5wywp41nqmsph1pv0-25bf7990
looking up default/github-com-j2sol-demobrigade-pulljob
Creating secret pulljob-1510015746257-25bf7990
Creating Job Cache PVC github-com-j2sol-demobrigade-pulljob
undefined
Creating pod pulljob-1510015746257-25bf7990
Timeout set at 900000
default/pulljob-1510015746257-25bf7990 phase Pending
default/pulljob-1510015746257-25bf7990 phase Failed
FATAL: job pulljob(pulljob-1510015746257-25bf7990): Pod pulljob-1510015746257-25bf7990 failed to run to completion (rejection)
error handler is cleaning up
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not sure what I can use to see what that rejection is, so far I've only known to get logs of the ephemeral worker pod, and then the pod the worker would create (only in this case job pod is never created).

Any help would be appreciated!

**Comment by adamreese** [comment]
First two checks...

`kubectl describe pod pulljob-1510015746257-25bf7990`

`kubectl logs pulljob-1510015746257-25bf7990`

**Comment by j2sol** [comment]
I suspect it's trying to get the commit `25bf7990b2c7f27fa94f1345fda79e97098735ee` from the target repo `j2sol/demobrigade`, but that commit lives in the fork, `jkeating/demobrigade`. But I can't tell, I don't see logs anywhere of any VCS fetching attempts. I could be way off.

**Comment by bacongobbler** [comment]
Is that pull request being triggered from https://github.com/j2sol/demobrigade/pull/5? If so that would be the right commit ID, so that doesn't seem to be the issue.

Can you get the logs from `kubectl logs pulljob-1510015746257-25bf7990 -c brigaderun`? Seems like the container exited with a status code of 128.

**Comment by j2sol** [comment]
I'm fairly new to k8s, I had thought that calling logs on the pod would bubble up any logs from any of the containers within the pod. 

That command returns the same:

```
> kubectl logs pulljob-1510015746257-25bf7990 -c brigaderun
Error from server (BadRequest): container "brigaderun" in pod "pulljob-1510015746257-25bf7990" is waiting to start: PodInitializing
```

**Comment by j2sol** [comment]
Oh! Running logs on the sidecar finally reveals something of interest:
```
> kubectl logs pulljob-1510015746257-25bf7990 -c brigade-vcs-sidecar
Cloning into '/src'...
fatal: reference is not a tree: 25bf7990b2c7f27fa94f1345fda79e97098735ee
```

That confirms my suspicion. The hash doesn't exist in the target repo. The target repo is `j2sol/demobrigade` and the pull request originates from `jkeating/demobrigade`. The hash itself lives in a branch on `jkeating/demobrigade`, but is also accessible as `refs/pull/5/head`:

```
> git remote show origin
* remote origin
  Fetch URL: git@github.com:j2sol/demobrigade.git
  Push  URL: git@github.com:j2sol/demobrigade.git
  HEAD branch: master
  Remote branches:
    j2sol-patch-1 tracked
    master        tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
master ~/src/demobrigade> git fetch origin pull/5/head:pr5
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From github.com:j2sol/demobrigade
 * [new ref]         refs/pull/5/head -> pr5
master ~/src/demobrigade> git show pr5
commit 25bf7990b2c7f27fa94f1345fda79e97098735ee
Author: jkeating <jlk@derpops.bike>
Date:   Mon Nov 6 16:48:11 2017 -0800

    content on readme

diff --git a/README.md b/README.md
index 4b7149b..39d8eb2 100644
--- a/README.md
+++ b/README.md
@@ -1,2 +1,4 @@
 # demoapp
 A simple demo python web app
+
+Add some content
```

**Comment by j2sol** [comment]
Unfortunately I don't know Go well enough to dig into Brigade to set the reference to check out correctly.

**Comment by u2takey** [comment]
This is a git issue, commit cannot be checked out if it is not merged in git-side-car. (Now in git-side-car, it just clone and checkout, right action maybe: init remote -> fetch -> checkout )
We need a more robust git-side-car to fix this.
A related issue: git clone is too much for build process, we should limit clone depth and tags.

**Comment by j2sol** [comment]
Yeah, looking at https://github.com/Azure/brigade/blob/master/git-sidecar/rootfs/clone.sh#L5 there should be another step as you say, to fetch a given ref, and then checkout the revision. That would mean adding an additional env var  to read from, and to populate within the hooks. For a push, the ref would be the branch/tag and the revision is the hash. For pull requests it's different, and doesn't directly come from anything in the web hook payload. It can be constructed from the data within though. Which, upon reading the edited comment to topping to drone-git, that does indeed look like what's needed here, albeit with adjustment in the hooks to produce those required vars.

**Comment by technosophos** [comment]
I started on a new version of the sidecar a little bit ago: #86 

Would @j2sol and @u2takey be willing to look at this and see if we could make it better? It's just Bash code at this point (which seems like the right way of doing things). Our first version of the sidecar was just really naive. I would like to make it much better.

**Comment by j2sol** [comment]
Yeah, I could offer some suggestions, not sure if I'll have time to throw code at it (plus getting through the paperwork at IBM to get the CLA signed...)

There's a deeper question to answer, and that is 

> What do I want tested?

The easy answer is

> the tip of the PR

because that's what the end user has submitted. However, that's not necessarily what will get merged, should the pull request be accepted.

Imagine if you will, a semi-busy repo, one that gets a handful of PRs each day, and a couple of them merged. If a contributor forks the repo on Monday, makes their branch and starts working, and on Wednesday they put up a PR, the tip of that PR is their change on top of Monday's code. But since Monday, the project has merged 4 new PRs. Testing the tip of the PR at this point is testing a dead end. That tree will not exist. What _would_ exist is the tip of that PR **merged** to the target branch. That is a much closer representation of the state of things should that PR be merged right at that moment. Call this the `speculative state`.

Getting to the speculative state is difficult, because it can depend on how a project is configured on GitHub to perform merges. GitHub "helpfully" offers many choices [here](https://help.github.com/articles/about-merge-methods-on-github/), and each of those choices produces a different state to speculate about. Which option to use to produce the speculative state could be a project level configuration when creating/modifying a project in Brigade, or it could be discovered dynamically by querying the API for the project (which would require further rights). Probably the easiest thing to start with is static config at the project level.

To get to this point iteratively, I would recommend updating the sidecar to first handle "tip of PR" testing. Once that's in shape, then go the next step of creating the default speculative state, which is the PR merged (--no-ff) to the target branch, and once that's in place, expand the merge options to support GitHub's other merge types via static config, and finally (optionally) dynamic discovery of merge method.

**Comment by technosophos** [comment]
Ah, yes. I see what you mean. /cc @adamreese

**Comment by mattfarina** [comment]
It might be worth looking at the CircleCI checkout [step](https://circleci.com/docs/2.0/configuration-reference/#checkout). [Here's an example from the charts repo](https://circleci.com/gh/kubernetes/charts/875). See the checkout code step.

In there you can see how the github pull request remote/checkout works if you start digging.

**Comment by j2sol** [comment]
As a data point, TravisCI tests the merger of the PR tip to the target branch: https://docs.travis-ci.com/user/pull-requests/#How-Pull-Requests-are-Tested

**Comment by j2sol** [comment]
As does Shippable: http://docs.shippable.com/ci/pull-request-builds/
