### ISSUE TITLE
Chore: brigade-worker/src/k8s.ts refactor into brigade-worker/src/k8s/*.ts

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#12]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-08-22 22:47:33_

----

The k8s.ts file is getting too big, and should be broken down into a subpackage.

**Comment by technosophos** [comment]
The related PR is now lost in the sands of time.
