### ISSUE TITLE
Potential security issue with brigade.js

### ISSUE THREAD

**Issue by j2sol** [Azure/brigade#120]
I couldn't find another method to communicate with the project, so apologies for dumping this here.

Having read through the design, and playing around with it for a bit, I think there is a rather important security concern that should be addressed.

From what I can tell, when reacting to `pull_request` events from GitHub, the intent[1] is to check out the tip of the pull request, and then process the `brigade.js` file within to decide what to do. On the surface, this seems like a great idea, as it allows proposing changes to code and/or the test runner and having that change used to test the proposal. Great way to get feedback on a change before committing it to the repo. However, when looking deeper, there is a flaw. The `brigade.js` file has a LOT of power. It can spin up all manner of resources, using all manner of images, and more disturbingly, it is the main way in which to expose secret data into the environment (and thus into containers). Total control is given to the `brigade.js` contents. When this is combined with the typical project workflow in GitHub, this means that anybody on GitHub can fork your repository, modify the `brigade.js` file to exfiltrate your secrets, and open a pull request to your project. If your project is configured to send web hooks, then Brigade will see the event, get the proposed content,  and execute it. All without human interaction. It's incredibly dangerous, and I don't see anything about this written into the Security concerns, nor any way to provide a human interstitial before Brigade triggers, to allow for a human to ensure nothing nefarious is in the pull request. One could limit the repo configuration for the web hook so that it only sends events on `push`, rather than on `push` and `pull_request`, but that means external contribution would be untested until merged into a branch on the repo.

Other systems that can deal with secrets typically limit configuration of how the secret is exposed, and do not allow proposed changes to alter that configuration. The way that Brigade is currently architected, I don't see this as possible.

It's entirely possible that I've overlooked some key thing that prevents all of this, and I'd be very happy to learn of that.

Cheers!

[1] #111

**Comment by j2sol** [comment]
It has since been pointed out to me that issue #22 is related to this.

**Comment by technosophos** [comment]
Wow, your timing is great. At the time you were posting this yesterday, @adamreese and I were discussing this exact issue! And I'll be working on it today.

We are looking at three solutions (not necessarily mutually exclusive):

1. Allow the admin to disable `pull_request` in the project config, and do this by default. I will very likely add this feature today.
2. Add a tainting mode (`disableSecrets=<boolean>` or `trusted=<boolean>`) to the event (which is generated by the gateway) to allow gateways to indicate that the `proj.secrets` object should not get populated. This is akin to what CircleCI does on PRs.
3. Add a whitelist of users who are allowed to use `pull_request`, and add that list to the Project config
4. Disallow execution of the `pull_request` event **IF** the `brigade.js` file is present in the list of files changed

There are a few combinations of the above that we could do, as well.

We are _hugely_ open to new ideas, @j2sol. So let me know if you (or anyone) has some other ideas. And also which (if any) of the above look good.

**Comment by j2sol** [comment]
There's lots of things that could be done, but really what you want is for humans with sufficient authority to look over proposed code before that proposed code makes use of secrets. It's beneficial to allow secrets to be used with pull requests, so that whether a change comes from within your repo or from a fork, you still go through the same CI paths. With an added human review before triggering the CI you allow for a human to spot any nefarious usage of the secrets.

In systems like [Zuul](https://docs.openstack.org/infra/zuul/), this is handled by having two types of pipelines with corresponding sets of triggers. There is a unreviewed pipeline, where every change is immediately executed on, and secrets are not allowed. This is typically triggered by a pull request open/reopen/modify, or by a comment such as `recheck`. Then there is a second pipeline type, where it's assumed a human has reviewed it. This pipeline is triggered by (or at least will bock until it receives) a human of sufficient authority to pass judgement on the change. The human can express this with a GitHub Pull Request Review, or adding a specific label to the PR. That pipeline would allow for secrets to be used.

This works, mostly because the definition of secrets and the use of the secrets is configuration that is outside of the repository being tested. A repository being tested CAN indicate which jobs to run, and can even create jobs within the repo, but it cannot define new pipelines, nor secrets, nor new jobs that make use of existing secrets.

Of course, this is a very complex setup, and may not match the intent of Brigade. What you've identified as some initial options would work, such as limiting whether or not a project COULD react to a pull_request, or by setting a taint flag if the brigade file is modified in the change. Although given how much power resides in the brigade.js file, it may make more sense to NOT consume it from the speculative state, unless otherwise directed by sufficiently authorized users.

**Comment by technosophos** [comment]
The GitHub webhook API does give access to comments on PRs. We could add something chat-ops like and say "if a comment by a member-of-sufficient-standing says 'run tests', trigger an event..."

We could make "member-of-sufficient-standing" simple (anyone with write or admin on the project) or make it highly configurable.

The cool thing about the Brigade architecture is that for the most part all of this logic is isolated to the GitHub gateway, so we don't need to worry about introducing massive amounts of complexity to Brigade.

**Comment by j2sol** [comment]
Yes, you can get events for comments, and for tags. A tag being added might be a better fit here, because only members with write access can apply a tag to a pull request, so you already know that the person who created the tag has sufficient standing.

**Comment by technosophos** [comment]
Was thinking about the tag scenario. What should we do in the case where:

- User opens PR
- Admin adds tag
- User adds another commit or force-pushes

Re-running the build automatically would be a security issue. Would we remove then re-add the tag to kick of a new run?

**Comment by j2sol** [comment]
When using a tag as a indication of approval, then when the system starts testing the change it should remove the tag from the PR. The tag was used as the trigger method for the change as it currently sits, so it can be removed. Further changes to the PR would require the tag being reapplied, which would in turn signal a new approval.

Instead of a tag, one could also use a pull request review. Providing an APPROVED pull request review (from somebody with write access to the repo) indicates human approval, which should suffice for using secrets. GitHub has a feature in that when new changes are made to the PR, it can dismiss any APPROVED reviews, so that humans must re-review the change. The only downside of PR reviews is that one cannot review one's own change, so as a repository owner if I create a pull request I cannot approve it (thus get secrets used). I have to have some other person with write access provide the review. Tags don't have this restriction, and may be more useful for smaller projects.
