### ISSUE TITLE
GitHub status payload has invalid url

### ISSUE THREAD

**Issue by j2sol** [Azure/brigade#126]
When a status is set on the commit, a URL is provided with it. However this URL appears to be broken:

```
{
  "id": 4312453694,
  "sha": "11426f2c689a6a7ccb78a6c6e366ce040e5f797d",
  "name": "j2sol/demobrigade",
  "target_url": "http://169.48.217.138:32586/log/j2sol/demobrigade/id/11426f2c689a6a7ccb78a6c6e366ce040e5f797d",
  "context": "brigade",
  "description": "Brigade build passed",
  "state": "success",
```

That IP and port is indeed the exposed service for the Brigade gateway service, but that URL results in a 404.

**Comment by technosophos** [comment]
Good catch. We removed that endpoint, and should fix that code.
