### ISSUE TITLE
GitHub gateway should silently ignore events which are not handled

### ISSUE THREAD

**Issue by j2sol** [Azure/brigade#127]
Currently when an event comes into the web hook that the gateway does not handle (anything other than `ping`, `push`, or `pull_request`), an `http.StatusBadRequest` is [returned](https://github.com/Azure/brigade/blob/master/pkg/webhook/github.go#L59). This in turn makes the GitHub project web hook settings show a littering of what looks like errors, specifically from things like `status` events, which wind up being generated by Brigade itself.

It would be better to silently accept the set of events from GitHub that COULD be sent, and only act on ones that Brigade wants to. The rest should just result in a quiet 200, like the `ping` event.

It's not an error that Brigade doesn't do anything with the events that can come at it.

**Comment by technosophos** [comment]
If Brigade can't deal with a request, shouldn't it return an error so that the user knows that Brigade can't do anything? I am a little worried that if we returned a success code, it would give the faulty impression that the hook was handled.

**Comment by bacongobbler** [comment]
How does other CI systems handle unknown events? We could model this from Circle/Travis and get an idea how we should handle this as precedent.

**Comment by j2sol** [comment]
If the consumer of Brigade is not the operator of Brigade, what can the end user do in this scenario? Maybe they could narrow down which events are sent. But, even within the pull_request event, there are things like labels added/removed etc. actions that Brigade does not act upon (yet it will accept the hook and return 200).

To me, returning something other than 200 indicates an error, and in some cases the end user may not be able to act upon that error. I would argue that it's worth logging to the Brigade install that an unhandled event came in, as the Brigade operator has the potential to update Brigade to handle those events. The Brigade system should return 200 indicating that it indeed got the hook and the payload signature matches.

If you ever move to making Brigade a GitHub App rather than a web hook, this is less of a concern, as the person who creates the App will see all the web hook data, rather than each repo that installs the app (to get the web hook running), and it's much more likely that the person creating the GitHub App is _also_ the Brigade operator.

**Comment by technosophos** [comment]
Yeah, that is a good point.
