### ISSUE TITLE
doc topic: logging in Brigade

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#13]
<a href="https://github.com/bacongobbler"><img src="https://avatars2.githubusercontent.com/u/1360539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bacongobbler](https://github.com/bacongobbler)**
_2017-08-23 17:30:11_

----

We should have a topic guide on how one can add log output to their jobs.

related tickets:

- #46

**Comment by technosophos** [comment]
Is the information in the [Scripting guide](docs/topics/scripting.md) sufficient?

**Comment by bacongobbler** [comment]
Yep!
