### ISSUE TITLE
Helm install fails with brigade/brigade repo per docs

### ISSUE THREAD

**Issue by squillace** [Azure/brigade#130]
According to https://github.com/Azure/brigade/blob/master/docs/intro/install.md#quick-install-guide: 
```
Add the Brigade repo: helm repo add brigade https://azure.github.io/brigade
Install Brigade: helm install brigade/brigade --name brigade-server
```
But, as of 9f69ad2, the result is 

```
➜  brigade git:(master) helm repo add brigade https://azure.github.io/brigade
"brigade" has been added to your repositories
➜  brigade git:(master) helm search brigade
NAME                       VERSION    DESCRIPTION
brigade/brigade            0.4.0      Brigade provides event-driven scripting of Kube...
brigade/brigade-project    0.4.0      Create a Brigade project
➜  brigade git:(master) helm install brigade/brigade --name brigade-server
Error: file "brigade/brigade" not found
```

related to #131

**Comment by technosophos** [comment]
I could not reproduce this one locally. I managed to get it to install the first time following your directions. But I have seen that problem happen when a networking error occurs. Would you mind trying again? I'll do the same here.

**Comment by squillace** [comment]
Yeah, I'm on zsh on Ubuntu 17.10. I'll drop into bash and retry, because I can repro no problem.

**Comment by squillace** [comment]
should we investigate a linux repro?

```
➜  brigade git:(master) bash
ralph@surfacebook:~/work/go/src/github.com/Azure/brigade$ helm repo add brigade https://azure.github.io/brigade
"brigade" has been added to your repositories
ralph@surfacebook:~/work/go/src/github.com/Azure/brigade$ helm install brigade/brigade --name brigade-server
Error: file "brigade/brigade" not found
```

I can share out my machine to you if you want to figure this one out. Helm 2.7.0.

**Comment by technosophos** [comment]
@squillace what's your Helm version? I just realized that for compatibility with ACS, I'm on 2.6.2.

Another command worth testing is `helm fetch brigade/brigade`. That will try to fetch just the chart.

I tested all of these commands again, and am not having problems. But here's my repo list just in case I'm missing something obvious:

```console
$ helm repo list
NAME      	URL
stable    	https://kubernetes-charts.storage.googleapis.com
local     	http://127.0.0.1:8879/charts
acid      	https://deis.github.io/acid
mattermost	https://releases.mattermost.com/helm
brigade   	https://azure.github.io/brigade
```

**Comment by technosophos** [comment]
Oh! Another possibility is a corrupted repo cache. Can you paste in the output of `cat $(helm home)/repository/cache/brigade-index.yaml`?

**Comment by squillace** [comment]
that's likely here, as I've used this machine well before release. I'll just dump it, unless you want it.

**Comment by squillace** [comment]
I wish that'd been it. I'm quite sure I'm doing something wrong, but damned if I know what it is.

```
➜  work tar -zxvf helm-v2.7.0-linux-amd64.tar.gz
linux-amd64/
linux-amd64/README.md
linux-amd64/helm
linux-amd64/LICENSE
➜  work sudo cp linux-amd64/helm /usr/local/bin
[sudo] password for ralph:
➜  work helm init
Creating /home/ralph/.helm
Creating /home/ralph/.helm/repository
Creating /home/ralph/.helm/repository/cache
Creating /home/ralph/.helm/repository/local
Creating /home/ralph/.helm/plugins
Creating /home/ralph/.helm/starters
Creating /home/ralph/.helm/cache/archive
Creating /home/ralph/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/ralph/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
➜  work helm version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
➜  work helm repo add brigade https://azure.github.io/brigade
"brigade" has been added to your repositories
➜  work helm install brigade/brigade --name brigade-server
Error: file "brigade/brigade" not found
```

**Comment by squillace** [comment]
➜  work helm fetch brigade/brigade
Error: Failed to fetch https://azure.github.io/brigadebrigade-0.4.0.tgz : 404 Not Found

I have a feeling we're missing a slash there.

**Comment by bacongobbler** [comment]
This may be due to https://github.com/kubernetes/helm/pull/3065 which was fixed in helm v2.7.1. Can you try upgrading and see if that's fixed?

**Comment by technosophos** [comment]
Oh, yeah... that would make sense. I tested on 2.6 and on 2.7.1 (well, `master` actually). So I would not have seen that issue

**Comment by squillace** [comment]
testing now! I bet you're right. I've upgraded to 2.7.2.

**Comment by squillace** [comment]
Closing: you hit it on the nose. all works now for the helm repo approach.

**Comment by jskulavik** [comment]
FYI for anybody interested, I'm setting up Draft, Helm, and Brigade on my Cloud Shell which now has Helm 2.7.0 already installed.  I ran into this same install issue and had to run the latest (2.7.2) in order to install the Brigade chart, i.e. `$ ./helm install brigade/brigade --name brigade-server`

**Comment by technosophos** [comment]
I guess we need to get the cloudshell team to update. Thanks for pointing that out.

**Comment by jaypaddy** [comment]
I'm seeing the following issue? Please pardon my naivety... just started digging in k8.
Error: apiVersion "batch/v1beta1" in brigade/templates/vacuum-cronjob.yaml is not available


root@DESKTOP:~# helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
root@DESKTOP:~# helm fetch brigade/brigade
root@DESKTOP:~# helm install brigade/brigade --name brigade-server
Error: apiVersion "batch/v1beta1" in brigade/templates/vacuum-cronjob.yaml is not available
root@DESKTOP:~#

**Comment by mumoshu** [comment]
Hi @jaypaddy, you need a newer k8s version or disable the vacuum feature completely. Please see #283 fore more info!

**Comment by jaypaddy** [comment]
Thank you @mumoshu. That worked. Brigade is now in my k8 cluster
