### ISSUE TITLE
No rule to make target 'build-client'

### ISSUE THREAD

**Issue by lukepatrick** [Azure/brigade#132]
Brig - Readme.md
https://github.com/Azure/brigade/blob/master/brig/README.md
Looking for simple binary build instructions

**Comment by bacongobbler** [comment]
Good catch. The correct incantation is `make build`, not `make build-client`. Feel like amending the documentation in a PR? :)

**Comment by lukepatrick** [comment]
sure
would a 
`
# Build native binaries client
.PHONY: build-client
build: brig
`

to the makefile add the desired command?

**Comment by bacongobbler** [comment]
I think just amending the README to use `make brig` instead would be the right approach.
