### ISSUE TITLE
event types in brigade.js use inconsistent naming scheme

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#149]
Pull request events use the event type "pull_request" while image push events from Container Registries use the event type "imagePush".

In javascript the common convention is to use camelCase for variable names. I would like to propose that event types should use camelCase moving forward.

This does introduce a breaking change to existing brigade.js files, but this is why we're not at 1.0 yet :)

**Comment by technosophos** [comment]
I think `pull_request` came from the way that GitHub names its webhooks, while I made up imagePush.

**Comment by technosophos** [comment]
PR #99 has a fix for imagePush -> image_push

**Comment by technosophos** [comment]
Fixed via #99
