### ISSUE TITLE
fix: move worker's destroyStorage to after 'after' event

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#15]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-09-08 00:43:55_

----

We might be able to give 'after' and 'error' access to shared storage if we move destroyStorage into the beforeExit handler.

**Comment by technosophos** [comment]
Fixed
