### ISSUE TITLE
If worker times out while PVCs provisioning, pods are orphaned

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#16]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-09-08 23:25:25_

----

Apparently, pods have no upper bound on the amount of time they will stay in state "pending" while waiting for storage to become available. So if the worker times out and kills storage, the pod can _never_ leave state PENDING. It will sit idle forever.

I guess the solution is to destroy pods on timeout? Or find a way to get pods to timeout and fail if PVCs never become available.

**Comment by squillace** [comment]
Just ran into this now with AKS cluster.

**Comment by technosophos** [comment]
At this point, a vacuum will eventually clean these up.
