### ISSUE TITLE
JS documentation needs to cover docker.enabled

### ISSUE THREAD

**Issue by technosophos** [Azure/brigade#165]
The JS documentation needs to have a section explaining the `Job.docker` object and using the Docker socket.

**Comment by bacongobbler** [comment]
https://github.com/Azure/brigade/blob/master/docs/topics/scripting.md#docker-runtime shows this off a little bit. What did you have in mind? I can tackle this if the existing documentation is insufficient :)

**Comment by technosophos** [comment]
It just need to be added here: https://github.com/Azure/brigade/blob/master/docs/topics/javascript.md#the-job-class
