### ISSUE TITLE
Privileged Jobs - Docker-in-Docker

### ISSUE THREAD

**Issue by lukepatrick** [Azure/brigade#173]
Question on Privileged Jobs:
Would it be possible to do a Docker volume mount? If I had a job to clone a repo and load that into a container.

    var test = new Job("test", "docker:17.06.0-ce")
    test.docker.enabled = true
    test.tasks = [
    "git clone somerepo",
    "docker run -t --privileged -v somerepo:/tmp/somerepo myImage:tag"
    ]

**Comment by bacongobbler** [comment]
Hmm, I haven’t tested volume mounts but I don’t think it will work as you expect, since I believe it mounts directories from where the docker daemon is running (the host) as opposed to the client. Feel free to give it a shot and report on what you find, though!

**Comment by lukepatrick** [comment]
Works like you mentioned, relative to the docker daemon and the host filesystem.
