### ISSUE TITLE
Job Tasks input by shell script

### ISSUE THREAD

**Issue by lukepatrick** [Azure/brigade#174]
Is there a way to have the Tasks of a Job load a shell script instead of an array of tasks?
I'm guessing the intended design, if running a long script would be to add that script to the project repo and have a task call the script from the Project storage, e.g. `task = ["./src/myscript.sh"]`

**Comment by bacongobbler** [comment]
yes, that would be the right approach :)

**Comment by lukepatrick** [comment]
Thanks!
