### ISSUE TITLE
Quesiton: Pull events, no poll?

### ISSUE THREAD

**Issue by lukepatrick** [Azure/brigade#177]
The only event triggers are based on push notifications from a webhook (i.e. github), correct?
If I have brigade behind my firewall I would need a public reverse proxy of some sort to get in.

No polling mechanisms?

**Comment by technosophos** [comment]
The design of Brigade goes like this:
- There's a controller that listens for events
- There's a gateway that generates the events

The gateway system is designed to be pluggable, so you can write your own gateways fairly easily. It should be possible to write one that polls an external source, or listens to a message queue or whatever you want.

I'll see if we can brush up the documentation on that. We've written some that are just simple shell scripts, and they work just fine. So hopefully the barrier of entry for writing a completely custom gateway is not too high.

**Comment by lukepatrick** [comment]
A custom gateway sounds great. I appreciate any documentation that can be put together.

**Comment by bacongobbler** [comment]
Here's a sample custom gateway that listens to trello webhook events: https://github.com/technosophos/brigade-trello

**Comment by technosophos** [comment]
Here's a shell script that I use inside of a Git receive hook for a version of Git that I run in cluster. It's really basic, but performs as a gateway. https://gist.github.com/technosophos/bd13903c536e7a07dd1a3c58aedea2c7

**Comment by technosophos** [comment]
Another option would be to write a simple CronJob  that would fire a `brig run` command at the right periodicity.

**Comment by technosophos** [comment]
I'm closing this since I don't think there's more to do. Feel free to re-open if necessary.
