### ISSUE TITLE
Make brigade.js optional from GW to Controller

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#19]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-10-04 17:28:14_

----

If no brigade.js is found, fall back to the repository

**Comment by technosophos** [comment]
Fixed.
