### ISSUE TITLE
Container Image Verify

### ISSUE THREAD

**Issue by lukepatrick** [Azure/brigade#193]
Running a Job with a container image that doesn't exist errors with a non-useful message:
`FATAL: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object. (rejection)`

How can we verify the image exists or improve error messaging before proceeding?

**Comment by adamreese** [comment]
I think this was the same issue reported in #139

**Comment by lukepatrick** [comment]
Similar error due to a 'missing' container, but different location (In a Job vs a Project sidecar)

**Comment by technosophos** [comment]
I believe this is fixed in 0.8. Can you let us know if it still seems broken?

**Comment by lukepatrick** [comment]
If I create a Job with a 'foobar' container, the job-pod itself will log an error:
```
$ kubectl log testjob-1516224363459-master
Error from server (BadRequest): container "brigaderun" in pod "testjob-1516224363459-master" is waiting to start: image can't be pulled
```

However, the Worker-pod will continue endlessly (well, until timeout..)
```
$ kubectl log brigade-worker-01c430762r2hpg69vjdvpjtgwz-master
==> Running Job
[brigade:k8s] Creating secret testjob-1516224363459-master
[brigade:k8s] Creating pod testjob-1516224363459-master
[brigade:k8s] Timeout set at 900000
[brigade:k8s] default/testjob-1516224363459-master phase Pending
[brigade:k8s] default/testjob-1516224363459-master phase Pending
.
.
.
.
```

**Comment by technosophos** [comment]
Okay, I will work on this.
