### ISSUE TITLE
Error event only has partial error information when using Group.runAll

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [Azure/brigade#217]
I am using `Group.runAll` to run two jobs. Both jobs are hardcoded to fail. When the error event occurs, the error information (reason field) suggests that only one of the jobs failed, when actually both jobs failed. 

Perhaps this is expected, but I feel it would be better when using `Group.runAll` if the error event reason contained information about all the jobs that failed. Furthermore, it might be better still to structure the reason as an array or an array of objects. This would allow developers to have an easier time sending user friendly notifications about all the jobs that failed, when a group of independent jobs run.

brigade.js
```
const { events, Job, Group } = require("brigadier")

events.on("timu", (e, project) => {
    var unitTestA = new Job("unit-test-a", "myimage")
    unitTestA.tasks = [
        "echo running unit tests for a",
        "exit 1"
    ]

    var unitTestB = new Job("unit-test-b", "myimage")
    unitTestB.tasks = [
        "echo running unit tests for b",
        "exit 1"
    ]

    Group.runAll([unitTestA, unitTestB])
    .then((result)=>{
        console.log("Done")
    })

});

events.on("after", (e, project)=>{
    console.log("AFTER event called", e)
})

events.on("error", (e, project)=>{
    console.log("ERROR event called", e)
})

```

Output of error event

```
ERROR event called { buildID: '01c18v9fpw2jyhjb1ac09j4pqs',
  workerID: 'brigade-worker-01c18v9fpw2jyhjb1ac09j4pqs-c11ce419',
  type: 'error',
  provider: 'brigade',
  commit: 'c11ce41976e121f325c6ecd85206264a3e4edca4',
  cause: 
   { event: 
      { buildID: '01c18v9fpw2jyhjb1ac09j4pqs',
        workerID: 'brigade-worker-01c18v9fpw2jyhjb1ac09j4pqs-c11ce419',
        type: 'myevent',
        provider: 'myevent',
        commit: 'c11ce41976e121f325c6ecd85206264a3e4edca4',
        payload: '' },
     reason: 'job unit-test-a(unit-test-a-1513199290026-c11ce419): Pod unit-test-a-1513199290026-c11ce419 failed to run to completion',
     trigger: 'unhandledRejection' } }
error handler is cleaning up
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bacongobbler** [comment]
I believe `runAll` is supposed to return a result which is [a list of all the results](https://github.com/Azure/brigade/blob/bee6c26c6906e18b9977b908e272e1ed6d00a86a/brigade-worker/test/brigadier.ts#L87-L90), though it's not clearly documented on how to use the result from `runAll` (I had to look through the source code to find the result). You could loop through the result and find out which jobs failed and which jobs succeeded. For example:

```
Group.runAll([unitTestA, unitTestB])
    .then((results)=>{
        for (let result of results) {
            console.log(result.toString())
        }
    })
```

Does that help answer your question? :)

**Comment by brandon-bethke-neudesic** [comment]
Thank you for the response. I investigated and `Group.runAll` is simply passing job.run() to `Promise.all()`, so in the case of an error the promise is rejected immediately and therefore it's not waiting for the result of the other jobs.  I was expecting `Group.runAll` to work something like this where the result of each job is captured and a final result is constructed:

```
    results = []

    var a = unitTestA.run()
    .then((result)=> {
        obj = {"unit-test-a": "PASS"};
        results.push(obj)
        return obj
    }).catch((err)=>{
        obj = {"unit-test-a": "FAIL"}
        results.push(obj)
        return obj
    });

    var b = unitTestB.run()
    .then((result)=>{
        obj = {"unit-test-b": "PASS"};
        results.push(obj)
        return obj;
    }).catch((err)=>{
        obj = {"unit-test-b": "FAIL"};
        results.push(obj)
        return obj;
    });

    Promise.all([a,b])
    .then((result)=> {
        console.log(result)
    });
```
