### ISSUE TITLE
Proposal: Make the shared space size configurable

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [Azure/brigade#220]
Is there a reason why the Build Storage (Shared Space) is not configurable when the Job Cache storage is? The shared storage size appears to be hardcoded to 50Mi.

I would like to be able to configure the Build Storage size just like the Job Cache size.

**Comment by technosophos** [comment]
That is a good idea. We might have to make it configurable at the project level, instead of within JS, but I will go look.
