### ISSUE TITLE
vcs-sidecar fails when passed a branch name and commit hash

### ISSUE THREAD

**Issue by blimmer** [Azure/brigade#228]
I encountered these failures when trying to build a branch with brigade.

## Branch Name
I noticed that the vcs-sidecar had a familiar exception (128) and that the whole job failed because of this. Here's the output from that container:

```console
kubectl logs do-nothing-1513714578597-test-ecr --namespace operations vcs-sidecar
+ : /src
+ : git@github.com:blimmer/k8s_deploy_demo.git
+ : test-ecr-pull
+ git clone --depth=50 git@github.com:blimmer/k8s_deploy_demo.git /src
Cloning into '/src'...
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
+ cd /src
+ git fetch origin test-ecr-pull
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
From github.com:blimmer/k8s_deploy_demo
 * branch            test-ecr-pull -> FETCH_HEAD
+ git checkout -qf FETCH_HEAD
+ git reset --hard -q test-ecr-pull
fatal: ambiguous argument 'test-ecr-pull': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

This problem occurs locally for me, too.

The solution is that, in the case of branches, you need to pass the `--branch=<branch-name>` parameter along with the `--depth` parameter. This is because the `--depth` parameter in `git` implies `--single-branch`, as well ([docs](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt))

The tricky part is that the `--branch` parameter can only accept named tags and branches, and cannot take a commit hash, so switching logic will need to be added for this case.

## Commit Hash
This one exited with exit code (1).

```console
+ : /src
+ : git@github.com:blimmer/k8s_deploy_demo.git
+ : 1353a9d889ae7ec6c53304c2abe893aa0aaee5d1
+ git clone --depth=50 git@github.com:blimmer/k8s_deploy_demo.git /src
Cloning into '/src'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
+ cd /src
+ git fetch origin 1353a9d889ae7ec6c53304c2abe893aa0aaee5d1
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
error: Server does not allow request for unadvertised object 1353a9d889ae7ec6c53304c2abe893aa0aaee5d1
```

Again, this is because of the depth issue. That command would work if `1353a9d889ae7ec6c53304c2abe893aa0aaee5d1` were the tip of the branch but, in this case it wasn't.

**Comment by blimmer** [comment]
I propose reverting the `depth=50` change commit to fix this in 0.7.0 and release a bugfix

https://github.com/Azure/brigade/commit/bb98a1f3b6fe21e94fb3e65742cc6c63f88a5ac0

**Comment by dunglas** [comment]
It will take again a very long time to clone large repositories. Can’t we use the branch name instead of the commit hash?

**Comment by dunglas** [comment]
Here are what Travis does:

```
git clone --depth=50 https://github.com/api-platform/core.git api-platform/core
cd api-platform/core
git fetch origin +refs/pull/1563/merge:
git checkout -qf FETCH_HEAD
```

**Comment by blimmer** [comment]
The reason Travis can do that is that they don't directly support building a commit hash (without knowing the branch). In the example you posted they're referring to a PR reference. Here's what they do when they're dealing with a branch:

```
$ git clone --depth=50 --branch=master https://github.com/blimmer/ember-braze.git blimmer/ember-braze
$ cd blimmer/ember-braze
$ git checkout -qf 10e2668e2e7a5a6418c2b7cfce6c17f561887cfd
```

or a named tag:

```
$ git clone --depth=50 --branch=v0.3.0 https://github.com/blimmer/ember-braze.git blimmer/ember-braze
$ cd blimmer/ember-braze
$ git checkout -qf v0.3.0
```

So I think we'd need to change the requirements for the hook to either:
a) require a branch name with commit hash
b) check out the whole repo in the case of a commit hash (and do the shallow clone for branches)

**Comment by mightwork** [comment]
How can I have the sidecar pull up a different branch other than master for my job? I am going through the documentation but can't find anything.
