### ISSUE TITLE
Thoughts on Reusability in Javascript Files?

### ISSUE THREAD

**Issue by blimmer** [Azure/brigade#240]
We plan to use brigade for a portion of our Continuous Delivery pipeline. That means that many of our projects will have very similar base `brigade.js` files defining the common pipeline.

Some of this re-usability will come from our common containers we use, however, if there are common tasks that we want to pipeline, it will require duplicated code in the `brigade.js` file.

For example, you could imagine a bunch of projects having this kind of brigade file:

```javascript
const { events, Job, Group } = require("brigadier")

events.on("exec", () => {
  var securityCheck = new Job("security-check", "our-k8s-deploy-container:latest", ["security_check"])
  var validateImage = new Job("validate-image", "our-k8s-deploy-container:latest", ["validate_image"])
  var somethingElse = new Job("something-else", "our-k8s-deploy-container:latest", ["something_else"])

  Group.runAll([securityCheck, validateImage, somethingElse]).then(() => {
     var deploy = new Job("deploy", "our-k8s-deploy-container:latest", ["deploy"])
     deploy.run();
  });
});
```

Because we want to parallelize all of the work done initially, we can't abstract this logic away into the container 100%. It'd be great if we could instead require a custom library that could keep all projects up to date with our current deployment pipeline. For instance:

```javascript
const { ourDeploy } = require("our-deploy-node-package")

events.on("exec", () => {
  ourDeploy.doEverything(); // this executes the Brigadier commands, but taking advantage of upstream improvements to the common node package (maybe adding new checks, documentation publishing, etc.)
});
```

As a platform infrastructure team, having the ability to continuously improve all consumers of our deployment without touching their repos is a big benefit in long-term maintainability.

What are the Brigade team's thoughts on something like this?

**Comment by technosophos** [comment]
I am very much open to ideas on this. One thing I have been pondering is allowing `require` to look up things in the Git repository that is associated with the project. The syntax would probably be:

```
const mylib = require("./mylib")
```
The question is then what we resolve `./mylib` to. Assuming `$GIT` is the path to the Git checkout of the Brigade project's associated VCS repo, I can thing of a few options:

- `$GIT/mylib`: Treat all libraries as "local" JS files
- `$GIT/node_modules/mylib`: Treat all libraries as Node libraries
- `$GIT/brigade_modules/mylib`: Invent a class of Brigade libraries

Or we could try to get more creative and fetch libraries from some other shared resource like a PVC or object storage or something. In that case, we might support a way of fetching/caching those libraries each time a worker is invoked.

**Comment by mumoshu** [comment]
> `$GIT/mylib`: Treat all libraries as "local" JS files

seems like necessary and sufficient for me.

For the second, perhaps we are not yet sure if we really want node_modules to be supported. In other words, are those really necessary to implement useful pipelines?
Also, assuming `brigade.js` is located at `$GIT/brigade.js`, I'd rather expect `require("mylib")` rather than `require("./mylib")` to be resolved to `node_modules/mylib`. In nodejs world, we don't use a relative-path to `require` a node module?

**Comment by mumoshu** [comment]
Taking both this and #250 into account, how about allowing to configure a default `brigade.js` plus library per project's values.yaml as a starting point?

```yaml
scripts: 
- path: brigade.js
  content: |
    ...
  path: our-deploy-package.js
  content: |
    ...
```

Or

```yaml
scripting:
  defaultBrigadeJs:
    content: |
      ...
  libraries:
  - path: our-deploy-package.js
     content: |
       ...
```

// I slightly prefer the former as it looks consistent between the definitions of default brigade.js and out-deploy-package.js

With this, an user could populate `content` from any source at project creation time, possibly with a script to append the `scripts/scripting` block to a YAML or a basic templating w/ sed/awk/text-template/etc.

**Comment by blimmer** [comment]
Hey @mumoshu - good timing. I actually talked with @technosophos about this yesterday. Here's what we're thinking, interested to get your thoughts on it.

Our use case is from the perspective of a platform infrastructure team providing pipelines out to our devs. We want to be able to have a JS package with common pipeline logic maintained by our team. We'd like for our consumers to be able to take advantage of new features implemented in this package in a seamless way. `npm` packages felt like the most natural way to distribute. It also sounds like @technosophos has heard requests to be able to source local `.js` files to reduce the length of `brigade.js` files. The two top-level concerns (local and remote JS) would be implemented as two distinct, but related, features.

Here's is what we came up with.

## Sourcing Local Javascript Files
We came up with two different options here.

### Allow the user to define additional source paths (Option 1)
In this option, the user could define, at the brigade-project level, additional folders within the repo to add to the NPM path. For example, given this repo structure:

```console
my_repo
├── brigade.js
└── brigadeFunctions
    └── mylogic.js
```

and a brigade-project configuration including this key:

```yaml
# values.yml within a brigade-project (see https://github.com/Azure/brigade/blob/master/charts/brigade-project/values.yaml)
# NOTE: feedback welcome on keys within this values file, this is just something I quickly came up with

brigadeRuntime:
   addToNpmPath:
    - "./brigadeFunctions"
```

Would then add the `brigadeFunctions` to the npm path such that you could then require those files directly like this:

```js
const { events, Job, Group } = require("brigadier");
const { myFunction } = require("./mylogic");
```

### Create a `.brigade` folder that other JS can live alongside (Option 2)
In this option, the user could create a `.brigade` folder, inside which is the `brigade.js` file and also other JS files that can be `require`-d from within the JS. For the visual folks:

```console
my_repo
└── .brigade
    ├── brigade.js
    └── mylogic.js
```

Then, within the `brigade.js` file, you could require it like this:

```js
const { events, Job, Group } = require("brigadier");
const { myFunction } = require("./mylogic");
```

We kind of liked this idea because it's similar to the [templates supported by GitHub](https://github.com/blog/2111-issue-and-pull-request-templates). The similarity between these ideas is that you can place the special github files (like `PULL_REQUEST_TEMPLATE.md`) either at the root of the directory, or within the `.github` folder. The same thing would go for the `brigade.js` file. It could either live at the root of the repo, or in the `.brigade` folder.

The only downside to this is that it's a little "magical" and not super declarative.

## Sourcing Remote `npm` Packages
We came up with one way that we really liked to handle this feature, but there are some decisions to be had within the plan. The idea here is that we'd add a new brigade-project value config that allows adding additional npm packages to the brigade-worker. That key would look something like this:

```yaml
# values.yml within a brigade-project (see https://github.com/Azure/brigade/blob/master/charts/brigade-project/values.yaml)
brigadeRuntime:
   packages:
    - name: "my_npm_package"
      version: "1.1.0"
```

Which would run the following within the brigade-worker:

```console
yarn add my_npm_package@1.1.0
```

We discussed a bunch of other options, but this felt the best of what we thought of.

### Caching
The outstanding questions here are with regards to caching. We don't want to have to run `yarn install` every time the workers spin up. Today, `brigadier` and the other node dependencies are build into the brigade-worker image, so we don't have to run the install every time. However, with the external dependency, we'll need to fetch and cache.

There are a few options we discussed:
- [Persistent Volume Claim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
- [Minio](https://www.minio.io/)

We were thinking an adapter model might be nice for caching these. Perhaps we default to PVC (since that should be doable for most people), with the ability to swap in a different caching adapter.

We'd cache the `node_modules` folder after running `yarn add`, then restore the cache so that the `brigade.js` has access to the libraries you've specified on future runs. The cache would be invalidated and recreated when the `brigadeRuntime.packages` content changes. Alternatively, we could always rebuild the cache anytime `brigadeRuntime.packages` is present, wiring into the [helm events](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md#the-available-hooks) for postInstall/postUpgrade.

## Conclusion
Comments welcome on this! Thanks for the time and consideration 😄

**Comment by mumoshu** [comment]
@blimmer Thanks very much for the detailed explanations!

I prefer the Option 2 plus a support for sourcing node modules as the combination of the two would provide the maximum reusability w/ a minimum configuration.

I don't really mind about the node module caching in the initial step. A node module containing several helper funcs to support writing brigade pipelines won't be that big? Then, caching seems like not a strict requirement for me.

**Comment by mumoshu** [comment]
@blimmer After thinking about this for a while, I came up with the 4th option.

## Allow the user to specify a custom brigade-worker image

which may contain any node modules or even any binaries to be used within a pipeline.

In your brigade project's values.yaml:

```
# OPTIONAL: Use this to customize the brigade worker which runs your brigade.js
worker:
  image: mumoshu/brigade-worker:v0.8.0-with-deps
```

In your Dockerfile:

```
FROM deis/brigade-worker:v0.8.0

RUN apk add --update --nocache <any-pkg-required-by-your-node-module>

RUN yarn add yourpackage@1.0.0
```

Or in case you'd like to include packages hosted in private Git repos:

```
FROM deis/brigade-worker:v0.8.0

# To avoid leaving your Git credential like a personal access token or a ssh private key,
# do `yarn add yourprivatepackage@1.0.0` outside of this docker-build and just add the package
ADD node_modules/yourprivatepackage node_modules/yourprivatepackage
```

Regarding U/X, it would look a bit cumbersome when what you wanted was just public npm module(s).

However, this 4th option would support many use-cases plus caching with a minimum change to brigade.

WDYT?

**Comment by blimmer** [comment]
@mumoshu this wasn't something that @technosophos and I thought of, but I agree that it's a simple idea and would be nice for my needs (private NPM package). It requires the least amount of work on the brigade side, too, but does have a somewhat higher barrier-to-entry for folks.

@technosophos what are your thoughts on this topic?

**Comment by mumoshu** [comment]
@blimmer Thanks for the comment!

> does have a somewhat higher barrier-to-entry for folks.

I agree with this.

So, even if we allowed users to customize which brigade-runner image to be used, it seems like a good idea for me to add one of options (1) to (3).

**Comment by mumoshu** [comment]
Just had a chance to look deeper into code-base and realized that we already have an ability to
customize brigade-worker image [per a brigade installation](https://github.com/Azure/brigade/blob/2f3eeb41eec7365b8f2b85dfff02f7d84da54bf3/charts/brigade/values.yaml#L66-L69).

```yaml
worker:
  registry: deis
  name: brigade-worker
  #tag:
  #pullPolicy: IfNotPresent
```

To actually support our use-cases, I believe adding similar option to brigade-project's values.yaml makes sense. WDYT @blimmer @technosophos?

**Comment by mumoshu** [comment]
Just submitted a PR #277 to illustrate my idea.

@blimmer @technosophos Would you mind reviewing? Thanks!

**Comment by technosophos** [comment]
Just catching up on all of this. Sorry for my silence on this issue as we got the last brigade release queued. I'll take a look at the PR.

**Comment by technosophos** [comment]
Okay, so as of Brigade 0.10.0, there is an image-based mechanism for adding both NPM packages and custom JS/TS libraries. It is something of a hybrid of all of the proposals in this issue. The documentation is here: https://github.com/Azure/brigade/blob/master/docs/topics/workers.md

Are there still cases we are not yet solving?

**Comment by blimmer** [comment]
This looks like a great implementation to start off with. From my perspective this covers the use-cases I was thinking of. I'm going to go ahead and close this issue and others can open up additional requests if it feels like there's something missing.

Thanks!
