### ISSUE TITLE
Brigade worker needs RBAC enabled

### ISSUE THREAD

**Issue by wstrange** [Azure/brigade#247]
In rbac enabled clusters, the default instructions:

`helm install brigade/brigade --set rbac.enabled=true`

do not create the required RBAC role for brigade worker pods. The pod will run brigade.js files, but will always fail at the end, presumably because the pod can not access some Kube API to update the status. 

I worked around this by doing a:
`kubectl create clusterrolebinding brigade --clusterrole cluster-admin --serviceaccount="default:brigade-worker"`

There is probably a smaller set of role capabilities that can be assigned.

Somewhat related to this, if the brigade worker attempts to run jobs like `helm` or `kubectl` - the RBAC permissions are also required. This is how I discovered the fix.

**Comment by wstrange** [comment]
I can see there is in fact a worker roles,sa and bindings created.

For whatever reason, things did not work until I created the clusterrolebinding above. 

Possibly the role is a) not sufficient or b) the pod is not getting created with the service account?

**Comment by mumoshu** [comment]
> Somewhat related to this, if the brigade worker attempts to run jobs like `helm` or `kubectl` - the RBAC permissions are also required. This is how I discovered the fix.

I have an exactly same use-case here so I've opened #251(I was too blind to notice this was relevant to me. Sry!)

With #251, you could create a serviceaccount yourself and then adds its name to the whitelist inside a brigade-project's config(values.yaml). You could override the serviceaccount to be used like `job.serviceAccountName= "mysa"` in `brigade.js` then. It is completely up to you what rolebindings you associates on the serviceaccount.
So, would #251 support your use-case, too?

**Comment by wstrange** [comment]
@momusoru - Yes, I think it would!

**Comment by technosophos** [comment]
@wstrange we think this was fixed in the last release. If you have a moment to re-test, can you let us know?
