### ISSUE TITLE
Reacting on GitHub events from a repository not containing brigade.js

### ISSUE THREAD

**Issue by mumoshu** [Azure/brigade#250]
Hi, thanks for maintaining this 👍 

To react events from GitHub, brigade seems to require a brigade.js in the root of each GitHub repository. This is slightly problematic to me because then I need to copy-paste or maintain a set of exactly same brigade.js across various projects.

So, I'd wanted to prepare a "default" brigade.js which is used when the repository which has emitted a github/brigade event misses its own brigade.js, so that I don't need this copy-pasting.

However, as far as I understand, brigade's GitHub-integration as of today seems to not allow this use-case out-of-box as [the GitHub gateway expects the repo emitted the event has a `brigade.js` in the repository root](https://github.com/Azure/brigade/blob/25b4e7990bcb02697ac7bbedd168beefef89c0f2/pkg/webhook/github.go#L208) and there is not way to inject brigade.js from an another source.

It seems like I can write my own brigade gateway based on the brigade's default gh gateway, which would load a default brigade.js from perhaps a global k8s secret containing it rather than the repo corresponds to the event coming from the gh gateway.

// My understanding behind this idea is that I could create a k8s secret representing [a build](https://github.com/Azure/brigade/blob/435cb75130758a3dda1638879525868c0dec1776/pkg/brigade/build.go#L20) which accepts an arbitrary "Script" to be executed by brigade, right?

But anyway, would it make sense it to support this use-case in the default GitHub gateway included in brigade? If so, any guidance/suggestion on how we should design it/other related use-cases should be covered together/etc.?

**Comment by technosophos** [comment]
Good question.

One possible approach would be to store a default brigade.js inside of the project. Then the order of scripting precedence would be:

- If the script is supplied in the event secret, use that
- Else if there is a brigade.js in the VCS repo, use that
- Else if there is a default brigade script in the project, use that
- Else fail

**Comment by mumoshu** [comment]
@technosophos Thanks! Regarding the implementation, I believe each Brigade gateway is responsible to load a script according to precedence you've noted, right?

**Comment by technosophos** [comment]
Yes

**Comment by cjhpaul** [comment]
I like the idea of having a default brigade.js as part of of a project. Is this feature work in progress?

**Comment by mumoshu** [comment]
@cjhpaul Not yet, at least on my side. Would you mind sharing your use-cases so that we can shape the design? Thanks.

**Comment by cjhpaul** [comment]
@mumoshu I was just thinking of a brigade project not associated with a git repository. At this point, the only option is to include a script content in an event every time it's sent.

**Comment by mumoshu** [comment]
@cjhpaul Thanks for sharing. Yeah, seems like so. Does that option work for you?

In my use-case, what I need is a default brigade.js used when brigade-github-gateway misses a brigade.js in the git repo/commit corresponds to a webhook event.

Creating a custom github gateway which picks a default brigade.js and include it in every event would definitely work for me.

However, in my understanding, that's exactly how an "officialish" github-gateway with support for the default brigade.js would look like 😄
