### ISSUE TITLE
OS not taken into account when scheduling a worker pod

### ISSUE THREAD

**Issue by OriYosefiMSFT** [Azure/brigade#253]
Hi, 

I have a hybrid cluster with 2 Windows nodes and 2 Linux nodes. When Brigade/K8s creates a worker pod, it sometimes fails to pull image because it tries to pull the Linux image on the Windows node. 
I believe a selector should be added to the worker spec. 
Thanks.

**Comment by technosophos** [comment]
Oh, yes, you are right. I will add a fix for that.
