### ISSUE TITLE
GitHub Integration: Support for more event types

### ISSUE THREAD

**Issue by mumoshu** [Azure/brigade#256]
According to the [code](
https://github.com/Azure/brigade/blob/08c49800425b5fd3babd2e98540fcd9d6fde6de9/pkg/webhook/github.go#L53), it misses support for types like:

- label
- deployment
- deployment_status

Especially, deployment* events are useful for my brigade pipeline to react on a gh's deployment
event(can be done with a simple curl) by triggering an actual deployment, instead of running a brig command or kubectl to trigger a brigade event directly.
It also provides nice notifications on the pull-request containing the git commit the deployment event refers, so that it looks more like a gh-native feature imho.

Would you mind if I contribute it?
Would there be more event types which should be supperted?
Any input would be welcomed. Thanks!

**Comment by technosophos** [comment]
We'll gladly accept PRs for any of the GitHub hooks. I am implementing them based on my guesses about what people want.

**Comment by technosophos** [comment]
Should we leave this open?

**Comment by mumoshu** [comment]
@technosophos Thanks for checking-in. No, I believe this can be closed now. Perhaps someone could open a separate issues for adding another event types with associated use-cases 😃

**Comment by mumoshu** [comment]
For anyone interested - When I had open this, I had somehow misunderstood that brigade doesn't support "pull request labeled/unlabeled" events. No, it isn't true.

It does emit `pull_request:labeled` or `pull_request:unlabeled` for the events. See `pkg/webhook/github.go` for more details!
