### ISSUE TITLE
Rename of GitHub gateway (brigade-gateway -> brigade-github-gateway)

### ISSUE THREAD

**Issue by blimmer** [Azure/brigade#264]
Now that gateways are more "microserice"-y (see #99), it might make sense to rename the github gateways.

I think it used to make sense when the gateway did both github and container registry, but I think a rename would be appropriate to make it clear what that gateway handles. It wasn't immediately obvious to me that the `brigade-gateway` was the github gateway until I dug into the code.

This ticket also relates to #263 as they might make sense to do together.

**Comment by technosophos** [comment]
Agreed
