### ISSUE TITLE
Initialize submodules in the default git-sidecar

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [Azure/brigade#269]
In the default vcsSidecar which clones the git repository, please add the feature to initialize the git submodules which may or may not be in the repository.

For example perform the following command ( or technical equivalent) at an appropriate time after the clone:
`git submodule update --init --recursive`

**Comment by mumoshu** [comment]
@brandon-bethke-neudesic Hi! I'm interested
but what do you mean by submodules and the default sidecar?
Examples of submodules would help. Thanks!

**Comment by brandon-bethke-neudesic** [comment]
Please see the updated description.

**Comment by technosophos** [comment]
Are there any potential negative side-effects to this for a typical Git repo? And would there be any reason to hide this behind a flag?

For example, do we want to require a user to add something like `initGitSubmodule: true` in the project in order to have the sidecar do the above? Or is it relatively safe default behavior?

**Comment by brandon-bethke-neudesic** [comment]
This line can go at the end of the current clone.sh script in git-sidecar.
`git submodule update --init --recursive`

This is where we put it in our custom git-sidecar, which is based on yours.

There is no negative side effect if the git repository has no submodules. The command will still return zero exit code.

I currently cannot think of a reason why this should be an optional setting. I have never had a reason to clone a repository but not get the submodules since one would only have part of the code.

**Comment by brandon-bethke-neudesic** [comment]
Resolved by https://github.com/Azure/brigade/pull/281
