### ISSUE TITLE
Feature: Add the ability to set Storage Class for PVC

### ISSUE THREAD

**Issue by torosent** [Azure/brigade#279]
Currently the 'default' storage class is used when creating a PVC. The ability to set storage class like [azurefile](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) would be great since now you have to override the 'default' storage class in AKS & ACS. 

I would be happy to implement it :)

**Comment by technosophos** [comment]
I was just playing with an NFS-backed storage system to use with Brigade, and you're right, we need a way to set the storage class so we can configure this more exactly.
