### ISSUE TITLE
Installlation Failure: apiVesion "batch/v1beta1" in brigade/templates/vacuum-cronjob.yaml is not available

### ISSUE THREAD

**Issue by smm190** [Azure/brigade#283]
I get the following error when attempting to install brigade server.

$ helm install brigade/brigade --name brigade-server
Error: apiVersion "batch/v1beta1" in brigade/templates/vacuum-cronjob.yaml is not available

**Comment by technosophos** [comment]
What version of Kubernetes? If you are pre-1.8, you will need to do `helm install brigade/brigade --name brigade-server --set vacuum.enabled=false` (that will actually work on any Kubernetes version, not just pre-1.8)

**Comment by technosophos** [comment]
Just to give context on what's going on there: The new Brigade Vacuum process uses the newer CronJob object, which didn't leave Alpha until Kube 1.8. That's the one that is causing the error above.

**Comment by smm190** [comment]
Thank you, this worked.  I am using Kubernetes 1.7.4.
