### ISSUE TITLE
Expose K8S service events

### ISSUE THREAD

**Issue by taliesins** [Azure/brigade#294]
My use case is that when we add/remove a service to K8S we want to configure Azure Application Gateway. I haven't find anything which does this currently. 

It would be nice to be able to script it simply in Brigade rather then write my own controller. I wish there was a page showing each of the event types, as currently I don't know what events are available.

I am hoping that we could extend:
https://github.com/Azure/brigade/blob/master/brigade-controller/cmd/brigade-controller/controller/informer.go

with something like:
https://github.com/beldur/kube2consul/blob/master/kube2consul.go

to expose K8s service events.

**Comment by taliesins** [comment]
Hi @mumoshu 

I realise it's possible to create custom bridges, but the effort required is far more then creating a K8s controller in go.

I think it's going to be a relatively common use case, anything that needs infrastructure coordination. So I don't see the harm in exposing these additional k8s events as we are already hooking into k8s events.

As a brigade noob I would have found a table of possible events (maybe include gateway that raises the event) extremely helpful.

**Comment by technosophos** [comment]
I've been sitting on this for a really long time because it's a little dangerous to configure, but... https://github.com/Azure/brigade-k8s-gateway

Just make sure you don't set it up to trigger a new build every time a new pod is created, otherwise you'll start an infinite loop. ;-)

**Comment by taliesins** [comment]
@technosophos thank you. This is exactly what I am after.
