### ISSUE TITLE
Native Cron Scheduling

### ISSUE THREAD

**Issue by smm190** [Azure/brigade#295]
Does brigade support scheduling the execution of jobs in a cron-like fashion?  Not seeing it anywhere in the docs.

**Comment by lukepatrick** [comment]
Nothing out-of-the-box that I'm aware of. There are a couple ways to do it yourself. 
You could put a cron on a `brig run` command.
The [Gateway docs examples](https://github.com/Azure/brigade/blob/master/docs/topics/gateways.md) discuss rolling your own cron-gateway.
