### ISSUE TITLE
Obsolete "Acid" references in docs

### ISSUE THREAD

**Issue by rektide** [Azure/brigade#3]
On the [design doc](https://github.com/Azure/brigade/blob/master/docs/topics/design.md) page, there are 11 different references to Acid (all in images). I'm pretty sure this is a previous name of the project?* I grepped a source checkout, & found no references to Acid.

* Ok, confirm, I can see some activity last week on this rename. #225.

**Comment by bacongobbler** [comment]
Thanks for bringing this up! As the first line suggests in the doc:

> *This document reflects an earlier state of Brigade, and needs updating.*

So yeah, we do need to give this design document a refresh. :)

**Comment by anguslees** [comment]
I note there are also several uses of "an brigade ..." in the text, so we also need additional proof-reading beyond the original (guessing mechanical) string replacement.

**Comment by adamreese** [comment]
cc\ @technosophos
