### ISSUE TITLE
RBAC for Vacuum?

### ISSUE THREAD

**Issue by mentalblock** [Azure/brigade#301]
When deploying Brigade through the Helm chart version brigade-0.9.0 into a non-default namespace, I get the following error from the vacuum jobs:

> secrets is forbidden: User "system:serviceaccount:$NAMESPACE:default" cannot list secrets in the namespace "$NAMESPACE"

As indicated above, it uses the default service account for the namespace and I am reluctant to give the 'default' service account more permissions.

Are there plans to create a service account and appropriate role/rolebinding for the vacuum job? Thanks.

**Comment by technosophos** [comment]
Just waiting to merge #290
