### ISSUE TITLE
Improve the developer doc about a workflow of rebuilding images and upgrading chart

### ISSUE THREAD

**Issue by mumoshu** [Azure/brigade#314]
I tend to run `make docker-build` and `helm upgrade ...` and then wait for components until they become ready.
How about adding a typical workflow like that to the developer doc?
So that developers could reliably/easily upgrade their local brigade installation with their latest changes.

**Comment by technosophos** [comment]
That's a good idea. Do you think we should document a minikube/Docker-for-Whatever flow, or a really generic flow? (e.g. with minikube, I do `eval $(minikube env)` so that I can push images directly into minikube's Docker daemon... not easy to do on something like AKS or GKE).
