### ISSUE TITLE
Public brigade pipeline for this repository to update pull-request statuses

### ISSUE THREAD

**Issue by mumoshu** [Azure/brigade#320]
I'd like any future pull request is built through a brigade pipeline, so that the PR status turns red once the build fails.

Would it be possible to officially run a brigade pipeline for this repository for that?

It will be even more nice if https://azure.github.io/kashti/#!/ could be turned into a web view of the public brigade pipeline which would be linked from pull request statuses.

@technosophos I'm happy to help anything I can do on my side.

Probably we aren't currently doing this due to any security consequence?
I wrote a possibly related issue #319.

**Comment by technosophos** [comment]
It's funny... I think all three of us came to the same conclusion at about the same time.

Today I spun up a new AKS cluster and set up Brigade. It's currently doing testing on the origin repo, but not PRs. When the AlloweAuthors PR is merged, I'll turn on PR functionality too.

**Comment by technosophos** [comment]
Still do need to get Kashti set up, though.

**Comment by technosophos** [comment]
Okay, it is now building on Master and building our PRs. THere's a bug in Brigade 0.11 that is sometimes reverting the status from Success to Building. I merged a patch for that in #379

**Comment by radu-matei** [comment]
Closing this we're now also using the Checks API and display the logs directly in the GitHub UI (on top of the public Kashti instance).
