### ISSUE TITLE
Helm install is broken

### ISSUE THREAD

**Issue by EdDraper** [Azure/brigade#322]
GitHub pages interface not working?

$ helm install brigade/brigade --name brigade-server
`Error: file "brigade/brigade" not found`

**Comment by radu-matei** [comment]
Did you first `helm repo add brigade https://azure.github.io/brigade` ?

**Comment by EdDraper** [comment]
yes

**Comment by technosophos** [comment]
What does `helm search brigade` show? If it shows nothing, try `helm update` and then re-try.

**Comment by EdDraper** [comment]
$ helm search brigade
NAME                    VERSION DESCRIPTION
brigade/brigade         0.9.0   Brigade provides event-driven scripting of Kube...
brigade/brigade-project 0.9.0   Create a Brigade project

**Comment by lukepatrick** [comment]
Which version of helm do you have installed? Have you recently updated? 
Trying a `helm repo update` may help
or the more dramatic fix: `rm -rf ~/.helm` removes helm repo, then: `helm init --client-only`
and start over, add any repo's you need (including brigade)

**Comment by technosophos** [comment]
It is starting to sound like your Helm repo index may be corrupt. You could try `helm repo remove brigade` and then try re-adding it. That will sometimes clean up the local cache. You can also try `helm fetch brigade/brigade`, which will attempt to download the chart, but not install it. But my guess is that if install won't work, neither will fetch.

Worst case, you can follow the alternate method in the Install docs and install straight out of the GitHub repo or just cd into `docs` and do `helm install ./brigade-0.9.0.tgz`

https://github.com/Azure/brigade/blob/master/docs/topics/install.md

**Comment by EdDraper** [comment]
Version sync problem with Helm.  Resolved.
