### ISSUE TITLE
Chart repository for Brigade gateways and other components

### ISSUE THREAD

**Issue by technosophos** [Azure/brigade#323]
One of the things we really want to do is make it easy for users to find additional Brigade components. We already have at least a half dozen Brigade gateways that can be installed with Helm.

How can we best set up a Brigade-specific chart repository that people can contribute their gateways to?

Some options:

- We could do a GitHub project
- We can set up a Chart Museum and host built charts there

**Comment by technosophos** [comment]
There's also KubeApps.

We could probably look into using GitHub with a Brigade hook to rebuild the index file each time a new chart is added.

**Comment by radu-matei** [comment]
I think https://github.com/Azure/brigade-charts (/gateways?) would be a good place for the gateways.

**Comment by lukepatrick** [comment]
We'll want to emphasize gateway and core versions compatibility; in docs if not in charts or other mechanism.

**Comment by radu-matei** [comment]
Closing this as https://github.com/Azure/brigade/pull/722 removed the charts, which are now available at https://github.com/Azure/brigade-charts.
