### ISSUE TITLE
Add Labels for Container Placement Constraints

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/brigade#325]
Given the efforts in place to integrate Azure Container Instances with Kubernetes clusters running in Azure, is there any way to ensure placement of Brigade pods onto ACI "nodes"? Likewise, if I have a container that could make use of GPUs, is there a way to force placement of the container on a node with GPU resources?

**Comment by technosophos** [comment]
You can pin to nodes on a per-Job basis using JobHosts (https://github.com/Azure/brigade/blob/master/docs/topics/javascript.md#the-job-class).

I'm not sure if there is a way to spin up workers on ACI instances. But if not, that would be fairly easy to add. We'd just have to decide whether it was a global setting or a per-project setting.

**Comment by dcieslak19973** [comment]
Will JobHost.name accept wildcards or does it need to be a specific hostname?

**Comment by technosophos** [comment]
I think it has to be a specific name. We pass it directly on to Kubernetes. Would it be more useful to support label selectors instead of a specific name?

**Comment by dcieslak19973** [comment]
I think adding support for labels (and keeping support for hostname) would be great. Especially for hybrid k8s clusters (both Windows and Linux agent nodes), being able to specify the OS for a container is huge.

The k8s-azure-container-instance "bridge" gives the ACI a single node in k8s, so name is probably sufficient to pin it. I'm not quite as sure how ACI works with GPU, but label selectors seem like they could be part of the solution.

**Comment by gfrankel97** [comment]
This should be mentioned in the docs, right now the docs only say it supports `os` and `name`. Label selectors are much more useful and had to go digging in the code and GitHub issues to find that functionality.
