### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/brigade#326]
Just curious when then next planned Brigade release is. The PVC fix is blocking our use-case.

Thanks
Dan

**Comment by lukepatrick** [comment]
Soon. @technosophos was working on the release before disappearing to the Helm Summit this week.

**Comment by technosophos** [comment]
Yeah, we hit a hiccup on release day, and then we were almost all gone for Helm Summit. So we're trying to get the next release ready now.

**Comment by dcieslak19973** [comment]
Looks like 0.10.0 is out. Will try it out next week and see if PVC works better. Closing this
