### ISSUE TITLE
Where do you go for help?

### ISSUE THREAD

**Issue by EdDraper** [Azure/brigade#334]
Where is the community for this project?  There is not even a twitter handle given...  I'm interested in how cron jobs are done.  Where the heck do I go?

**Comment by mumoshu** [comment]
Hi @EdDraper!

We have a dedicated channel named `#brigade` in the k8s official slack org: http://slack.k8s.io/

Regarding cronjob, it is matter of just running `kubectl create -f secret-representing-brigade-build.yaml` via k8s cronjob. A working example can be found at https://github.com/Azure/brigade/blob/675df3d4fbb9dc61f872fa0c2cc18bcdf30561a4/docs/topics/examples/simple-event/cron/cron-event.sh#L24

And I'm not really happy to say something like this but you'd better not use a word like `heck`!
I'm always here to help you without such words.
But I guess you had considerable frustration while adopting brigade. I feel very sorry about that. That's not what we want.
Maybe we'd better open a dedicated github issue to discuss how we could improve brigade doc about your use-case?
