### ISSUE TITLE
How to install the brig client

### ISSUE THREAD

**Issue by JCzz** [Azure/brigade#351]
Hi

Reading this: https://azure.github.io/brigade/topics/projects.html

It uses/mentions the brig client, but how and where to install brig client?

I found make but it failed(note I did set go path: GOPATH=`pwd`):

go get -u github.com/golang/dep/cmd/dep
go get -u github.com/alecthomas/gometalinter
gometalinter --install
make: gometalinter: No such file or directory
make: *** [vendor] Error 1

Thanks

**Comment by radu-matei** [comment]
Try with `make bootstrap brig`.

**Comment by JCzz** [comment]
Thanks @radu-matei

Just tried that:
```
make bootstrap brig
go get -u github.com/golang/dep/cmd/dep
go get -u github.com/alecthomas/gometalinter
gometalinter --install
make: gometalinter: No such file or directory
make: *** [vendor] Error 1

```

**Comment by radu-matei** [comment]
It seems as you don't [have your GOPATH setup correctly](https://golang.org/doc/code.html#GOPATH)

**Comment by JCzz** [comment]
Thanks

I followed this: https://github.com/Azure/brigade/blob/master/docs/topics/developers.md

I guess the vendor error is some vendor code that fails?

Setting:

```
$ mkdir -p $(go env GOPATH)/src/github.com/Azure # GOPATH is set to $HOME/go by default
$ git clone https://github.com/Azure/brigade $(go env GOPATH)/src/github.com/Azure/brigade
$ cd $(go env GOPATH)/src/github.com/Azure/brigade
Note: this leaves you at the tip of master in the repository where active development is happening. You might prefer to checkout the most recent stable tag:

$ git checkout v0.11.0
Building Source

To build all of the source, run this:

$ make bootstrap build
To build just the client binaries, run this:

$ make bootstrap brig
```

**Comment by JCzz** [comment]
I got it to build after:
1. dep ensure -v
2. make bootstrap build
3. make bootstrap brig

**Comment by technosophos** [comment]
We're testing binary builds, so hopefully we'll have nice downloads soon.

**Comment by technosophos** [comment]
Binary builds are posted now!
