### ISSUE TITLE
API feature: Swagger for automatically generating clients

### ISSUE THREAD

**Issue by seanknox** [Azure/brigade#353]
This would be super helpful, as with Kashti or any Brigade API client it's required to build the API client by hand each time.

**Comment by seanknox** [comment]
@radu-matei if @technosophos and @adamreese think this is worthwhile this might be a good pickup opportunity for you.

**Comment by lukepatrick** [comment]
Looking to investigate this issue. Wanted to see if there was any life to this issue before getting too far.

Saw some tools like [gin-swagger](https://github.com/swaggo/gin-swagger) and similar that provide some comment-based 'annotation' and generator tools. Though these don't play well with the current Brigade packaging (no 'cross-package models').

**Comment by radu-matei** [comment]
Yeah, I'm not a big fan of annotations to be honest...

**Comment by lukepatrick** [comment]
but we love them in Java...

Yeah, annotations are not really the gopher way it seems. 

Other ideas include swapping out the Gin framework for something like [go-restful](https://github.com/emicklei/go-restful) that can generate Swagger spec from your code.

Also, starting with an interface-first approach. Take your bespoke hand crafted interface (manually written swagger spec) and generate server code with [go-swagger](https://github.com/go-swagger/go-swagger)

**Comment by lukepatrick** [comment]
@seanknox I've been kicking around a swagger solution going with the above ideas.
You're welcome to try it out, feedback welcome. Published an [api container](https://hub.docker.com/r/lukepatrick/brigade-api/tags/)
and you can update your brigade (assuming v0.13.1) registry:
```bash
helm upgrade brigade brigade/brigade --set api.registry=lukepatrick
```
the swagger/openapi spec will be available at
`http://localhost:7745/apidocs.json`
