### ISSUE TITLE
Request: new API endpoints

### ISSUE THREAD

**Issue by seanknox** [Azure/brigade#354]
Placeholder issue for more API endpoints. I'll split these out into separate issues if these sound reasonable (already filed #352)

* **/project/:project_id**
  - individual project, all data

* **/projects**
  - project build object
  - all project data
  - last build, all data (nested)

* **/build/:build_id/**
  - individual build data
  - nested in it: jobs, logs

* **/builds/:project_id**
  - builds for that project

* **/jobs/:build_id**
  - zero or more jobs that build

* **/build_logs/:log_id**
  - zero or more logs for build log

* **/job_logs/:log_id**
  - zero or more logs for job log

**Comment by technosophos** [comment]
@seanknox  How do you distinguish between build logs and job logs? Right now we have:

```
	p := server.Project()
	rest.GET("/projects", p.List)
	rest.GET("/project/:id", p.Get)
	rest.GET("/project/:id/builds", p.Builds)
	rest.GET("/projects-build", p.ListWithLatestBuild)

	b := server.Build()
	rest.GET("/build/:id", b.Get)
	rest.GET("/build/:id/jobs", b.Jobs)
	rest.GET("/build/:id/logs", b.Logs)

	j := server.Job()
	rest.GET("/job/:id", j.Get)
	rest.GET("/job/:id/logs", j.Logs)
```

I can do one `logs/:id` endpoint, and basically have the ID be either a job or a build ID. But that seems a little bit unclear.
