### ISSUE TITLE
Job pods not created with provided service account

### ISSUE THREAD

**Issue by jchanam** [Azure/brigade#355]
Hi, I'm trying to use brigade with a custom service account name.

The brigade controller is receiving it correctly on the environmental variable `BRIGADE_WORKER_SERVICE_ACCOUNT` and It is creating correctly the worker with the SA provided.

The issue I've found is that the jobs are not created with this custom SA, they are being *tried* to create with the default (causing an error: `'pods "unit-test-01c8cz01sm8rdak2erk8j8vem3" is forbidden: error looking up service account test-workspace/brigade-worker: serviceaccount "brigade-worker" not found'`)

I think this jobs have to be created with the same, custom, service account. To do so, the Worker pod could be created also with the SA environmental variable, so it can create the job pods with it. Then, the code of the worker has to read this environmental variable, and create the pod with the SA.

I've managed to create the workers with the service account provided (or the default one instead), but I'm not able to edit the worker code to create the jobs pods correctly.

**Comment by jchanam** [comment]
On this branch, the changes on the controller are already done: https://github.com/jchanam/brigade/tree/create-worker-with-sa-env

Hope it helps or reduce needed work to do.

**Comment by technosophos** [comment]
Closed via #356
