### ISSUE TITLE
Source code in job?

### ISSUE THREAD

**Issue by JCzz** [Azure/brigade#359]
Hi reading this tutorial on creating a CD/CI using brigade:

https://azure.github.io/brigade/intro/tutorial04.html

How does it get the source code. I can see that the project file is containing the repo. but how to set the folder location/path?

I am asking because I would need to set GOPATH etc. if it is a go program.

Thanks It looks really cool

**Comment by technosophos** [comment]
For an example of working with GOPATH in a `brigade.js`, check out the CI setup for Brigade itself: https://github.com/Azure/brigade/blob/master/brigade.js#L9-L36
