### ISSUE TITLE
Execute termination actions on `error` lifecycle event

### ISSUE THREAD

**Issue by slok** [Azure/brigade#364]
At our pipelines, we try to use the `after` and `error` lifecycle events in order to set Github statuses. The problem is that the `after` ones are correctly set, but the `error` ones no, Is like if this event handler doesn't wait until everything is finished (in very few cases the GitHub status job pod triggers and when this happens the github status pod finishes after the worker has finished). I guess that has something to do with this.

https://github.com/Azure/brigade/blob/a140145cd4200e9be358165978f0344c3a374a41/brigade-worker/src/app.ts#L106-L106

We are not "catching" errors when executing jobs or groups because this could make repetitive to handle in all different kind of event flows (push, pull_request, exec...). 

Are we doing something wrong?

**Comment by technosophos** [comment]
To make sure I understand, you have an error handler like this:

```javascript
events.on("error", () => {
  console.log("do something");
});
```

But that error handler is never called?

It _should_ be the case that the default `error` handler is called last. But maybe there is a bug and it's either being called first or not being called at all.

**Comment by slok** [comment]
Yeah, it's called, but it doesn't wait to finish the handler.

Here is an example of a `brigade.js` file to reproduce the problem:

```js
const { events, Job } = require("brigadier");

function exec(cmd) {
    let goBuild = new Job("brigade-test", "busybox");
    goBuild.tasks = [cmd]
    goBuild.run()
}

function sleepWithLog(ms, msg) {
    return new Promise(resolve => {
        console.log(msg)
        setTimeout(resolve, ms)
    });
}

function debug(e, project) {
    let times = 20
    let sleepMS = 500

    let sleepLoop = sleepWithLog(sleepMS, "------------------------start------------------------")
    Array.from({ length: times }, (x, i) => {
        sleepLoop = sleepLoop.then(() => sleepWithLog(sleepMS, i))
    });    
    sleepLoop = sleepLoop.then(() => sleepWithLog(sleepMS, "------------------------end------------------------"))

    Promise.resolve(sleepLoop);
}


events.on("exec", () => {
    exec("echo 1")
});
events.on("exec-error", () => {
    exec("exit 1")
});

events.on("after", debug);
events.on("error", debug);
```

Doing `brig run` works ok, doing `brig run -e exec-error` doesn't.

**Comment by technosophos** [comment]
Hmmm... this might be an esoteric issue with the way Node does the event handling. Once we sleep, Node will consider that part of the current tick to be done, and may then go on and execute the next event handler. That handler will exit the process. I'll have to see if there is a good way to work around that.
