### ISSUE TITLE
Cannot run "push" command from the developers documentation

### ISSUE THREAD

**Issue by blimmer** [Azure/brigade#366]
Following the instructions here:

https://github.com/Azure/brigade/blob/master/docs/topics/developers.md#minikube-configuration

It says:
> Running `VERSION=latest make docker-build docker-push` will push the Brigade images to the Minikube Docker daemon.

But this doesn't work for me. I get a permission denied error because it's trying to publish out to docker.io.

```console
> VERSION=latest make docker-build docker-push
docker push deis/brigade-api:latest
The push refers to a repository [docker.io/deis/brigade-api]
ba7576f5d121: Preparing
b7c3763077f3: Preparing
cd7100a72410: Preparing
denied: requested access to the resource is denied
make: *** [brigade-api-push] Error 1
```

A few thoughts:

* The list of addons in that document state that the minikube addon `registry` should be disabled, but I think it needs to be enabled for this to work
* The makefile, I believe, needs to point at the local registry, instead of docker.io? I'm not super-familiar with the minikube registry though.

**Comment by lukepatrick** [comment]
Doing
`$ eval $(minikube docker-env)`
and running `VERSION=latest make docker-build` (without push) should be all you need. This will build into the minikube docker repo
Do you see the images in `$ docker images`?

btw, my current minikube:
```bash
$ minikube addons list
- addon-manager: enabled
- coredns: disabled
- dashboard: enabled
- default-storageclass: enabled
- efk: disabled
- freshpod: disabled
- heapster: disabled
- ingress: enabled
- kube-dns: enabled
- registry: disabled
- registry-creds: disabled
- storage-provisioner: enabled
```

**Comment by technosophos** [comment]
Yeah, we need to fix that in the docs. @lukepatrick is right.

Option 1: Remove the reference to `make docker-push`

Option 2: Explain how to set it up to point to your own registry and then do a `make docker-push`

I think I am leaning toward Option 1, since what we're really trying to explain is local dev workflow. What do you think?

**Comment by blimmer** [comment]
I think Option 1 is probably the way to go. I opened a PR to update this.
