### ISSUE TITLE
Error: timeout waiting for build 01c... to start

### ISSUE THREAD

**Issue by JCzz** [Azure/brigade#372]
Hi

Update:
I found that: `kubectl logs brigade-brigade-vacuum-...` is failing with the following:
```
Pruning records older than 2018-02-14 18:45:59.128294176 +0000 UTC m=-2591999.929197262
Error: secrets is forbidden: User "system:serviceaccount:default:brigade-brigade-vacuum" cannot list secrets in the namespace "default": Unknown user "system:serviceaccount:default:brigade-brigade-vacuum"
```

Following this tutorial from 1-4: `https://azure.github.io/brigade/intro/tutorial03.html`

I get a webhook error in GitHub that says: `We couldn’t deliver this payload: Service Timeout`

I am using the url as described in the tutorial: `http://x.x.x.x:7744/events/github`

Can I test that the `http://x.x.x.x:7744/events/github` is actually working?

Note I did get the external ip from: `kubectl get service`

Also if I do:
`brig run -f brigade.js someAlias/uuid-generator`
I get:
`Error: timeout waiting for build 01c8q4zn6qc4g110dzn6fj134g to start`

Note: I can see my project with: `brig project list `
Name, ID, Repo
`someAlias/uuid-generator	brigade-aa680...	github.com/someAlias/uuid-generator
`

I also have a ton of:
`brigade-server-brigade-vacuum-1521176400-dvncc      0/1       Pending             0          5h        <none>       <none>
`
when calling: `kubectl get pods`

Any help is appreciated

Regards
Christian

**Comment by technosophos** [comment]
/cc @bacongobbler 

I believe the source of this error is RBAC. When you installed Brigade, did you set `rbac.enabled=true`? (That may also be the issue with your Vacuum stuff)

**Comment by JCzz** [comment]
Hey @technosophos 
/cc @bacongobbler

You are so right, thanks it worked - really nice! 
Now I can start to play :-)

Regards
Christian

**Comment by technosophos** [comment]
Good! RBACs are a little bit of a pain to get set up. Sorry that slowed you down.

**Comment by JCzz** [comment]
Thanks

2018-03-19 19:01 GMT+01:00 Matt Butcher <notifications@github.com>:

**Comment by JCzz** [comment]
Hi @technosophos 

I am back with the same problem even with the rbac.enabled=true bouth for installing brigade and for the project.

```
brig run -f brigade.js deis/empty-testbed
Event created. Waiting for worker pod named "brigade-worker-01ch3gf2zmh249yjk1vy5p7b9t".
Error: pod failed to schedule: 
```

I dont know how to debug this. There is no vacume I can `kubectl log` on.

Do you have any idea? Thanks

This time I am running on Google Kuberneres Engine

I am running Helm & kubectl:

```
helm version
Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
