### ISSUE TITLE
brigade-brigade-vacuum

### ISSUE THREAD

**Issue by JCzz** [Azure/brigade#373]
Hi

I have a ton of pods named: `brigade-brigade-vacuum` with a status of `CrashLoopBackOff, Error, Pending, ContainerCreating`.

What is it and how to delete them?

**Comment by technosophos** [comment]
First, can you post some logs using `kubectl logs $VACUUM_POD_NAME` so we can figure out why it's failing?

Second, to delete them you can do `kubectl delete job -l role=vacuum`

Third, you can completely disable the vacuum by doing `helm upgrade $BRIGADE_NAME brigade/brigade --set vacuum.enabled=false`

The job of the vacuum is to delete old builds out of your cluster. So if it's possible to run it, it's a good idea. But there are enough oddities in the CronJob system in Kubernetes that sometimes disabling it is better.

**Comment by JCzz** [comment]
Thanks

Your answer #373 did the trick. Now it is not failing anymore an I was able dele all the failing ones.

Thanks

**Comment by technosophos** [comment]
Great! I'll mark this as closed.
