### ISSUE TITLE
brigade-worker error in kubernetes 1.9.3

### ISSUE THREAD

**Issue by gzlj** [Azure/brigade#376]
command: brig run cass/helloworld -f brigade.js 
I use the same value.yaml and brigade.js on kubernetes 1.9.3, and error occured like this:

[brigade:k8s] default/brigade-hello-compile-1521168778235-master phase Pending
[brigade:k8s] default/brigade-hello-compile-1521168778235-master phase Failed
[brigade:app] error handler is cleaning up
[brigade:app]   Error: job brigade-hello-compile(brigade-hello-compile-1521168778235-master):   Error: Pod brigade-hello-compile-1521168778235-master failed to run to complet  ion
  
  - brigadier.js:55 jr.run.catch.err
    ./dist/brigadier.js:55:35
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
	
	
It runs successfully on kubernetes 1.8.

**Comment by gzlj** [comment]
version
brigade:0.7
brigade-project:0.7

**Comment by gzlj** [comment]
brigade 0.11 runs sucessfully on k8s 1.9.3

**Comment by technosophos** [comment]
Can you do a `kubectl logs brigade-hello-compile-1521168778235-master vcs-sidecar`?

I'm guessing that when we did a breaking change to the `deis/vcs-github` image, it caused this problem. You might have to do something like `helm upgrade my-project brigade/brigade-project --set vcsSidecar=deis/vcs-sidecar:v0.11.0`

**Comment by radu-matei** [comment]
Closing this as it has been stale for a while - but feel free to reopen. 

Thanks!
