### ISSUE TITLE
Domain question: difference between a project worker and a build worker?

### ISSUE THREAD

**Issue by seanknox** [Azure/brigade#384]
I'm trying to model some mock data for Kashti and am wondering what the difference is between a "build" and "project" worker object:

Build:
```typescript
export class BuildWorker {
  constructor(
    public id: string,
    public build_id: string,
    public project_id: string,
    public start_time: Date,
    public end_time: Date,
    public exit_code: number,
    public status: string
  ) {}
}
```

Project:
```typescript
export class Worker {
  constructor(
    public registry: string,
    public name: string,
    public tag: string,
    public pullPolicy: string,
  ) {}
}
```

Accompanying JSON:
- project: http://acid-api.technosophos.me:7745/v1/projects
- build: http://acid-api.technosophos.me:7745/v1/project/brigade-29d38c7477ecee18e184b69bec354fc350605c51bc16d4dd2b6073/builds

**Comment by technosophos** [comment]
There is only one worker model. The `class BuildWorker` above looks right to me.

Projects returns just the last worker for that project, while project/:id returns all of the recent workers for that project

I'll have to look into why the projects workers are not being populated in your first query.
