### ISSUE TITLE
`brigade proxy` hardcoded to "default" namespace

### ISSUE THREAD

**Issue by jdotjdot** [Azure/brigade#387]
It appears as if the `brigade proxy` command is hard-coded to port forward only to the "default" namespace.  This seems like it should not be hard-coded and instead be passable via CLI or the current `kubectl` namespace.

Locations of this:
* https://github.com/Azure/brigade/blob/master/brig/cmd/brig/commands/proxy.go#L61
* https://github.com/Azure/brigade/blob/master/brig/cmd/brig/commands/proxy.go#L67

**Comment by radu-matei** [comment]
Great catch, thanks!
One question would be if we want to support different namespaces for the namespace and Kashti.

cc @technosophos

**Comment by radu-matei** [comment]
Great catch, thanks!
Fix started in #388
