### ISSUE TITLE
How to use entrypoint

### ISSUE THREAD

**Issue by smm190** [Azure/brigade#411]
I am using brigade to launch a docker container.  In my dockerfile, I use the ENTRYPOINT keyword like so:

ENTRYPOINT ["python3", "runMyScript.py"]

If I were to run this container via the command-line, I would do something like this to specify a config file parameter:

sudo docker run -it containerName--ConfigFile "config/config.txt"

I noticed that if I add "--ConfigFile config/exampleconfig.txt" to the tasks of my brigade job, brigade complains because it doesn't know what to do with this string; it is expecting something like "python3 runMyScript.py --ConfigFile=config/exampleconfig.txt".

We want to be able to bake the entrypoint into our dockerfile and pass command-line parameters for the python script through the brigade.js file to customize the run.  I.E. I want to be able to mimic the behavior of the "sudo docker run -it containerName --ConfigFile config/config.txt" command in my brigade file.

Does brigade support this behavior?

**Comment by technosophos** [comment]
We have not tried to replicate that behavior before. What if we implemented something like this?

```
var j = new Job("j", "myImage:latest")
j.args = [
  "--ConfigFile 'config/config.txt'"
];
```

Behind the scenes, we'd stop it from generating a wrapper script, and would just pass the args in directly.

**Comment by jdotjdot** [comment]
I'd personally prefer `args` to `tasks`.  I like having as much exposure to the Kubernetes YAML directly as I can. In fact, I'd be fine with even just being able to stuff regular Kubernetes JSON into a Brigade `Job`--that way I get full control.

I guess it depends on who Brigade is for--if it's for the knowledgeable Kubernetes admin or if it's for users who shouldn't need to know that much about Kubernetes.

**Comment by smm190** [comment]
I agree with @jdotjdot -- I also like args idea & the more exposure to the Kubernetes YAML, the better for us.
