### ISSUE TITLE
Add caching in Brigade API server

### ISSUE THREAD

**Issue by technosophos** [Azure/brigade#433]
Some of the calls on Brigade API take way too long to execute every single page load, and are amenable to caching.

Prime example: `/projects-build`

**Comment by walialu** [comment]
I second that! We have about 30 projects (or so) so far and the brig-api takes about 10 seconds to load the `/projects-builds` endpoint.

**Comment by jensneuse** [comment]
I'm currently in the works of solving the problem:
https://github.com/jensneuse/brigade/tree/improve-brig-api-performance

I've introduced a cache.NewListWatchFromClient for both secrets and pods which drops the request time for `/projects-builds` to <100ms.

Currently everything works fine running locally on my local machine. However I'm having issues passing all tests. Aside from that it looks like the current implementation of fake.NewSimpleClientset() doesn't work as expected for ListWatchers which makes it hard to unit test this scenario. (Maybe I oversaw something) Help is highly appreciated.

I'm looking forward to getting feedback on whats needed to get this into the upstream.

**Comment by jensneuse** [comment]
I was able to resolve all the issues, tests are passing now. I'd be happy to get feedback on the PR. Cheers
