### ISSUE TITLE
Support uncolorized output with brig

### ISSUE THREAD

**Issue by TimJones** [Azure/brigade#438]
When I use brig with a [solarized](https://github.com/altercation/solarized) colorscheme on my terminal emulator, the colorized output from `brig` is unreadable. Notice the text after `TypeError` is the same color as the background. I end up haveing to copy & paste the text somewhere else to read the output.

![image](https://user-images.githubusercontent.com/113170/39239308-c02fe248-4880-11e8-96d0-870e773884b8.png)

Adding a `--no-color` flag or similar would be a great help.

**Comment by technosophos** [comment]
This might be a little tricky since the colorized output is coming from a remote server, not the local client. We can probably strip color codes before sending the output to STDOUT, though. Thoughts, @adamreese ?
