### ISSUE TITLE
how to deploy custom helm charts

### ISSUE THREAD

**Issue by ESTrainer** [Azure/brigade#453]
I'm been reading the tutorials but could not find details on how to deploy custom helm charts. I want to replace our existing `JenkineFile` deployment with `brigade.js` but could not figure it how. 

Let say i want to deploy two helm charts by passing `key values`, by changing the `key and values` only but doesn't need to build the docker images as they already exists and just have to deploy helm chart in the kubernetes cluster. I appreciate if you any help me with it?

Example:

In JenkinFile i have the following stage step, I would like to test it with `Brigade`
```
    stage('Staging Deployment') {
      when {
        expression { env.BRANCH_NAME == 'master' }
      }

      environment {
        RELEASE_NAME = 'seanmeme-staging'
        SERVER_HOST = 'staging.seanmeme.k8s.prydoni.us'
      }

      steps {
        sh '''
          helm upgrade --install --namespace staging $RELEASE_NAME ./helm/seanmeme --set image.tag=$BUILD_ID,ingress.host=$SERVER_HOST
        '''
      }
      steps {
        sh '''
          helm upgrade --install --namespace staging $RELEASE_NAME ./helm/seanmeme2 --set image.tag=$BUILD_ID,ingress.host=$SERVER_HOST
        '''
      }
}
```

**Comment by ESTrainer** [comment]
Ok, I was able to jump start on it with the help of this [repo](https://github.com/charter-ctec/brigade-openstack-helm). 

I was trying to add a private `helm repo` but it fails. 

brigade.js
--
const { events, Job, Group } = require('brigadier');
const util = require('util')

const HELM_VERSION = "v2.8.0"

const CONTAINER = "lachlanevenson/k8s-helm:" + HELM_VERSION


events.on('exec', function (event, project) {
    console.log("........hello.................")
    // env info
    // console.log("==> Project " + p.name + " clones the repo at " + p.repo.cloneURL)
    // console.log("==> Event " + e.type + " caused by " + e.provider)

    // create job with name and container image to use
    var helm_job = new Job("helm-job", CONTAINER) // runs helm_job 

    //set up tasks   
    helm_job.tasks = []

    helm_job.tasks.push("helm repo add kube-orchestration <url of private github>");
    helm_job.tasks.push("helm ls");

    console.log("==> Set up tasks, env, Job ")
    //debug only
    //console.log(helm_job)

    console.log("==> Running helm_job Job")
    // run Start Job, get Promise and print results
    helm_job.run().then(resultStart => {
        //debug only
        console.log("==> Start Job Results")
        console.log(resultStart.toString())
        console.log("==> Start Job Done")
    })
});

events.on("error", (e) => {
    console.log("Error event " + util.inspect(e, false, null) )
    console.log("==> Event " + e.type + " caused by " + e.provider + " cause class" + e.cause + e.cause.reason)
})

events.on("after", (e) => {  
    console.log("After event fired " + util.inspect(e, false, null) )
});

Error
---
```
brig run bacongobbler/uuid-generator -f brigade.js
Event created. Waiting for worker pod named "brigade-worker-01cdd4xvk8v7ft9xbc7gr6mvbj".
Started build 01cdd4xvk8v7ft9xbc7gr6mvbj as "brigade-worker-01cdd4xvk8v7ft9xbc7gr6mvbj"
prestart: src/brigade.js written
[brigade] brigade-worker version: 0.13.1
[brigade:k8s] Creating PVC named brigade-worker-01cdd4xvk8v7ft9xbc7gr6mvbj
........hello.................
==> Set up tasks, env, Job
==> Running helm_job Job
[brigade:k8s] Creating secret helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj
[brigade:k8s] Creating pod helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj
[brigade:k8s] Timeout set at 900000
[brigade:k8s] default/helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj phase Pending
[brigade:k8s] default/helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj phase Failed
done
  Error: Pod helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj failed to run to completion

  - k8s.js:417 k.readNamespacedPod.then.response
    ./dist/k8s.js:417:32


[brigade:app]   Error: job helm-job(helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj): Error: Pod helm-job-  01cdd4xvk8v7ft9xbc7gr6mvbj failed to run to completion

  - brigadier.js:56 jr.run.catch.err
    ./dist/brigadier.js:56:35


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


Error event { buildID: '01cdd4xvk8v7ft9xbc7gr6mvbj',
  workerID: 'brigade-worker-01cdd4xvk8v7ft9xbc7gr6mvbj',
  type: 'error',
  provider: 'brigade',
  revision: { commit: '', ref: 'master' },
  logLevel: 1,
  cause:
   { event:
      { buildID: '01cdd4xvk8v7ft9xbc7gr6mvbj',
        workerID: 'brigade-worker-01cdd4xvk8v7ft9xbc7gr6mvbj',
        type: 'exec',
        provider: 'brigade-cli',
        revision: { commit: '', ref: 'master' },
        logLevel: 1,
        payload: '' },
     reason:   Error: job helm-job(helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj): Error: Pod helm-job-  01cdd4xvk8v7ft9xbc7gr6mvbj failed to run to completion

  - brigadier.js:56 jr.run.catch.err
    ./dist/brigadier.js:56:35


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7

,
     trigger: 'unhandledRejection' } }
==> Event error caused by brigade cause class[object Object]Error: job helm-job(helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj): Error: Pod helm-job-01cdd4xvk8v7ft9xbc7gr6mvbj failed to run to completion
[brigade:app] error handler is cleaning up
[brigade:k8s] Destroying PVC named brigade-worker-01cdd4xvk8v7ft9xbc7gr6mvbj
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node --no-deprecation ./dist/index.js
Directory: /home/src
Output:
".
```

**Comment by ESTrainer** [comment]
Seems like `brigade.js` does not provide the error description but upon looking the logs of the `job` pod, it is clear why it was failed. 

```
 kubectl logs helm-job-01cdd8xmcwk9889qre9kvb123e
Error: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```
https://github.com/Azure/brigade/issues/427 helped to find the logs.

**Comment by jensneuse** [comment]
Do you tell the helm cli where tiller is? (by setting the env correctly)

`var deployJob = new Job("deploy", "lachlanevenson/k8s-helm:v2.7.2", [
    'cd /src/',
    `${statusCommand} && ${upgradeCommand} || ${installCommand}`
  ]);

  deployJob.env = {
    'HELM_HOST': p.globalSecrets.HELM_HOST
  };
`
This is how we run helm from within brigade.
We've introduced our own worker image that injects global secrets (which you don't have to do but we found it useful). You can simply hardcode tiller service dns into the job env.

**Comment by technosophos** [comment]
Sorry for the long delay. I was on vacation this week. I think @jensneuse is right. But you will also need to run `helm init --client-only` right before you do `helm repo add` because the local init process creates the local chart cache.

For getting the logs of a brigade run, the `brig build logs` command (or the `brigadeterm` project from @slok ) are good ways of debugging.

Hope that helps!
