### ISSUE TITLE
Manual Triggers

### ISSUE THREAD

**Issue by bsomogyi** [Azure/brigade#458]
I'm just starting to evaluate Brigade for our CI/CD.  I didn't see it anywhere (or atleast it wasn't obvious), but is there a recommended approach for handling manual triggers?  I'd like to get to a point where they are not needed, but currently in our pipeline we need to have  a few manual gates to proceed to the next state. Thanks!

**Comment by technosophos** [comment]
We don't yet have a job, though, that stops an in-progress pipeline. It should not be hard to do at all... it'd be a matter of creating a Docker image that blocks until it receives some external "OK", and then continues. Then you would just do something like:

```javascript
events.on("someEvent", () => {
  const manualGate = new Job("wait-for-manual-ok", "some/pausecontainer")
  // Do some other stuff...
  manualGate.run().then(() => {
    // Do the rest of the pipeline
  })
})
```

I guess the main question is what the manual gate would do. It could start up a web server, listen on a chat server, listen on an event queue...

**Comment by bsomogyi** [comment]
Yeah - that is what I was looking to understand @technosophos.   We have the need to approve the pipeline to proceed to the next state on several occasions.  Thanks for the guidance...just starting to work with Brigade.  Feel free to close this issue/question off if you'd like.

**Comment by bsomogyi** [comment]
Closing the issue.
