### ISSUE TITLE
how do you re-run a previous build with brig CLI?

### ISSUE THREAD

**Issue by Strandedpirate** [Azure/brigade#463]
Scenario: builds are executing from git pushes to github or bitbucket. These builds are CI/CD and at some point we need to roll-back a deployment to a previous one using a specific build #.

How do I re-run a previous brigade build through the CLI using a specific brigade build #?

This seems to be missing:
e.g. `brig run myproject --buildId 01ce2w3w016kz6hqf9k8tmb3dn`
In this scenario I would expect brigade to lookup the buildId, gather the Event data from it and start a new build with that event data.

**Comment by technosophos** [comment]
All of that said... I could really use that for what I am working on _right now_. ;-)
