### ISSUE TITLE
If a Job.env{} var is empty, it will cause a Kubernetes error

### ISSUE THREAD

**Issue by technosophos** [Azure/brigade#469]
Consider this:

```javascript
j = new Job("foo", "alpine:3.7")
j.env = {
  foo: null
}
```

The above will create a Kubernetes pod with this in the env section:

```json
          {
            "name": "foo",
            "valueFrom": {}
          }
```

The above is invalid. It should be:

```json
          {
            "name": "foo",
            "value": ""
          }
```

Or something else that is structurally allowed.

The code that generates this is in the worker's `k8s.ts` file somewhere.

**Comment by jdotjdot** [comment]
This one's my fault.  It's these lines:

https://github.com/Azure/brigade/blob/a2646de88d941a4921b0cf805d108fe4a2f6f8f1/brigade-worker/src/k8s.ts#L216-L243

This could be fixed by adding another part to the if-statement at line 234, something like:

```javascript 
} else if (val === null) {
   envVars.push({
     name: key,
     valueFrom: {
       secretKeyRef: {
         name: secName,
         key: ""
       }
     }
  } as kubernetes.V1EnvVar);
} else {
// ...
```

**Comment by shubheksha** [comment]
I can pick this up!

**Comment by technosophos** [comment]
@shubheksha excellent! Thanks!

**Comment by shubheksha** [comment]
@biskit1, I'm on the move for a bit, so I won't be able to, you can pick it up!

**Comment by biskit1** [comment]
Thanks @shubheksha! Will try to get this done over the weekend. Will keep you posted!

**Comment by biskit1** [comment]
Just to update anyone who comes around: I'm trying to figure out how to set up the dev environment so I can run/implement the appropriate tests once I make the small change suggested above. 

I had to prioritize some other things given the time I estimated setting this up/figuring it out would take, so I just want you to know that I'm still on it and will complete it ASAP. 

If anyone (@jdotjdot , @technosophos) has some suggestions for setting up the dev environment just for this portion, please share :) for now, I'm getting started by following the steps listed in this [developers guide](https://azure.github.io/brigade/topics/developers.html) to get the appropriate tools installed and set up the environment.

**Comment by dgkanatsios** [comment]
closing since #670 has been merged
