### ISSUE TITLE
Document for GitHub integration with brigade seems to be outdated

### ISSUE THREAD

**Issue by disha94** [Azure/brigade#471]
Hi All,
I tried exploring brigade, and was following the tutorial for setting up the integration with github:
https://azure.github.io/brigade/intro/tutorial04.html
But was getting "undefined" with "e.commit", I tried a lot of things but seemed to be working, so I checked on your slack community and someone suggested to replace "e.commit" with "e.revision.commit".

This worked and its running fine now. Thanks a lot. But I request you to please update your docs so that no one else faces the same issue.

**Comment by technosophos** [comment]
Sure! Please do!
