### ISSUE TITLE
[brig] Windows binary has no .exe extension

### ISSUE THREAD

**Issue by f0** [Azure/brigade#472]
The Windows binary from the download section has no .exe suffix, without the .exe suffix windows don't know how to handel the binary.

Please provide the precompiled binary with a .exe suffix

**Comment by radu-matei** [comment]
@f0 - Thanks for letting us know!
In the meantime, as a quick fix, you could manually add the `.exe` extension and it should work (just tested on my Windows machine).

**Comment by f0** [comment]
@radu-matei  yes, manually adding .exe does wrok
