### ISSUE TITLE
Release Application Fail when trying brigade with draft

### ISSUE THREAD

**Issue by disha94** [Azure/brigade#483]
Hi All,
I am trying to integrate draft and brigade, as a result I have created a "brigade.js" script consisting of all the necessary steps for draft installation and running. Also, I am using ECR for image registry.
But unfortunately, as a part of **"draft up"** , the docker image build and push process are working fine but the **"Release Application"** phase is **"Failing"**.

I can't even check the logs as it is all running in the container and once it fails, the pod goes to "Completed" state.

Can you guys suggest if I am missing something, maybe with respect RBAC as that same thing is working all good in my local (ie without brigade when I am trying to run in a docker container), or if there is a way to get draft logs on console??
Really need help to debug this as its a blocker for me.

**Comment by bacongobbler** [comment]
After debugging offline, it turns out that the brigade-worker running `draft up` did not have read access to the default namespace, which is actually due to a bug in Helm: https://github.com/kubernetes/helm/issues/2611

**Comment by bacongobbler** [comment]
after applying the RBAC roles and rolebindings to grant birgade-worker access to read namespaces in the default namespace, all was well. Let's follow up in kubernetes/helm#2611 to fix the underlying issue. Thanks!
