### ISSUE TITLE
No JobCache size setting

### ISSUE THREAD

**Issue by TimJones** [Azure/brigade#490]
I am trying to implement a job cache but noticed the PVCs are created with the default 5MB allocation. Job storage has `buildStorageSize` but it looks like there is no equivalent for job cache (https://github.com/Azure/brigade/blob/master/brigade-worker/src/events.ts#L150).

**Comment by technosophos** [comment]
For job cache, size is set in `brigade.js` via `myJob.cache.size = ...`.
