### ISSUE TITLE
Brigade Gateway with Draft issue

### ISSUE THREAD

**Issue by emichaf** [Azure/brigade#491]
**Validating Brigade & Draft**

**Versions:**
Brigade 0.14.0
Draft 0.15.0
Helm 2.8.2

**Followed the instruction under:**
  Related Projects
   - Draft Pack for Building Custom Gateways: Build your own gateway in 5 minutes
      https://github.com/technosophos/draft-brigade

**The project could be used with brig and brigade.js file** -> 
          brig run -f brigade.js  brigade-3c505132ca6bd762bfe6732256e15684510bbcdb72333ed1cf1b88
                output: successful

**But when trying to use the same Brigade project with Draft, then it's failing:**

$ curl -XPOST http://localhost:57399/v1/webhook/myevent/brigade-3c505132ca6bd762bfe6732256e15684510bbcdb72333ed1cf1b88
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     70      0 --:--:-- --:--:-- --:--:--    70Internal Server Error

$ draft connect
Connect to chart:8080 on localhost:57399
[chart]: yarn run v1.5.1
[chart]: $ node index.js
[chart]: Running on 192.168.6.218:8080
Your connection is still active.
Connect to chart:8080 on localhost:57399
**[chart]: project brigade-3c505132ca6bd762bfe6732256e15684510bbcdb72333ed1cf1b88 could not be loaded**
  

**Healthz is working**
curl localhost:57399/healthz  -> ok

Any ideas?

**Comment by radu-matei** [comment]
@emichaf - do you have RBAC enabled on your cluster?

**Comment by bacongobbler** [comment]
Additionally, can you run a `helm list` for your cluster? According to the error, the custom brigade gateway cannot find the project in the same namespace as it was deployed. By default Draft is configured to deploy applications in the default namespace, so if you have brigade running in another namespace (say, `brigade`), then you'll need to change the `namespace` field in draft.toml, run `draft delete` and `draft up` again. :)

Hope this helps!

**Comment by technosophos** [comment]
Oh, @radu-matei is right. I am missing the role definition in that chart. Fixing.

**Comment by emichaf** [comment]
**All components are in the "**default**" namespace:**
- brigade-server (started with rbac.enabled=true)
- brigade-project (started with rbac.enabled=true)
- mygateway (started with rbac.enabled=true)

**Still same fault when trying 
curl -XPOST http://localhost:55622/v1/webhook/myevent/brigade-ae8de7d2d6004665f92fa350d2cd6f260a6a326f580df3c9502574**

Connect to chart:8080 on localhost:55622
[chart]: yarn run v1.5.1
[chart]: $ node index.js
[chart]: Running on 192.168.167.97:8080
**[chart]: project brigade-ae8de7d2d6004665f92fa350d2cd6f260a6a326f580df3c9502574
could not be loaded**

Trying to run via brig -f, and it's working for the project:
brig run -f brigade.js brigade-ae8de7d2d6004665f92fa350d2cd6f260a6a326f580df3c9502574
ok

**Comment by technosophos** [comment]
Okay, I know this is a bit tedious, but it will help us figure out where the problem lies.

While your `mygateway` is running, can you:

`kubectl exec -it YOUR_GATEWAY_POD_NAME /bin/sh`

Then install kubectl in the pod: 

```
$ curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
$ chmod +x ./kubectl
```

Then check to see if you can see the project secrets:

```
$ ./kubectl get secret -l component=project
```

If you. see the projects there, we can definitely rule out RBAC and we are down to two things:

- Did the gateway auth correctly?
- Is there a bug in the project-fetching code?

If the kubectl command _doesn't_ show the project, then the most likely culprit is RBAC.

**Comment by emichaf** [comment]
found some errors in the draft-brigade proj, se PR:

https://github.com/technosophos/draft-brigade/pull/1
