### ISSUE TITLE
Is worker supposed to be destroyed after job is done? 

### ISSUE THREAD

**Issue by YaraMohammed** [Azure/brigade#498]
I have a question I've a simple job to run a helm chart so the after the chart is deployed brigade worker pods keeps running, Is the worker suppose to keep running after deploying the chart? If so Is there an option to destroy after job done?

**Comment by technosophos** [comment]
The worker will be in state `Running` from when it comes online to when the last job terminates. Then the worker will clean up some things and exit. You will still be able to see the worker with `kubectl get pods` until the worker pod's record has been destroyed. That will happen either when Kubernetes cleans it, or when `brigade-vacuum` cleans it. At that point both its configuration and its log files will be gone, and you will no longer be able to `brig rerun` that job or see it in the Kashti/brigadeterm dashboards.

It is possible to keep the worker from exiting when jobs are complete. This can happen if you start an operation that does not exit when pods exit (for example, via a `setInterval()`). So it's possible that something in the code could prevent the worker pod from exiting the Running phase, but only if you scripted it to do this.

**Comment by YaraMohammed** [comment]
@technosophos  you are right I opened a connection and didn't close so the issue was in the code.
