### ISSUE TITLE
How to monitor brigade?

### ISSUE THREAD

**Issue by YaraMohammed** [Azure/brigade#499]
This is a question, What is the best way or practice to monitor brigade?

**Comment by technosophos** [comment]
What kind of monitoring do you have in mind? I would guess that the usual routes (Prometheus, for example) would be good for monitoring the lower-level parts like job/worker runtime and resource usage. For high-level stuff, right now the best tooling is the API serve and Kashti.

**Comment by technosophos** [comment]
Any update on this?

**Comment by YaraMohammed** [comment]
I didn't try to use prometheus but I was trying to install Kashti from the chart and I provided the apiServer service as described in the documentation
```
brigade:
  apiServer: "http://brigade-brigade-api:7745"
```
but I get an empty ui with no projects or anything and when I inspect the page I get this error
`Failed to load resource: net::ERR_NAME_NOT_RESOLVED http://brigade-brigade-api:7745/v1/projects-build` although if I do `wget http://brigade-brigade-api:7745/v1/projects-build` I can get the file

**Comment by radu-matei** [comment]
Hey, @YaraMohammed!
We're in the process of releasing a new version for Kashti and we have a release candidate that should work properly:

```
helm install -n kashti ./charts/kashti --set brigade.apiServer=http://<your-api-svc>:7745,image.repository=deis/kashti,image.tag=v0.3.0-rc1
```

In the future we will remove the need to manually pass the Brigade API server, but for now we still have to pass it - make sure to put the name of your Brigade API service, which depends on the name of your Brigade release.

Let us know how this works and any feedback you might have on Kashti!

**Comment by YaraMohammed** [comment]
Thanks @radu-matei looks like it's working fine now if I have any feedback I will open issue with it for sure.

**Comment by slok** [comment]
Maybe this could interest you @YaraMohammed :)
- https://github.com/Azure/brigade/pull/620
- https://github.com/slok/brigade-exporter
