### ISSUE TITLE
Running brigade on a production cluster side-by-side with production applications

### ISSUE THREAD

**Issue by Strandedpirate** [Azure/brigade#501]
Is there any precedence or official guidance (pros/cons) for running brigade in the same cluster that is running one's production applications? Taints/tolerations for node isolation perhaps or a resounding "don't do it"?

Has there been success or failure stories that can be shared with brigade specifically?

e.g. running builds/deployments through brigade using the same k8s nodes that are backing your production applications?

The [brigade-k8s-gateway](https://github.com/Azure/brigade-k8s-gateway) appears to require brigade to be running in the same cluster in order to gain it's benefits. Are there any plans to perhaps have that project turn into a "push" model that sends restful requests to another brigade instance just like how the webhooks work for github and bitbucket? e.g. cluster-A sends k8s events to cluster-B that has brigade installed.

**Comment by technosophos** [comment]
You should _definitely_ run Brigade in its own namespace. And RBAC is strongly encouraged. But when it comes to running on your prod cluster, it should be okay. We run ours on our production cluster, but our cluster is also relatively lightly used. Accounts on our prod cluster are also restricted to only highly trusted accounts.

On the k8s gw, I will have to look into that. I mean, it should be possible to have something collect k8s events and publish somewhere like a Kafka queue, and then write a Brigade GW that consumes the queue.
