### ISSUE TITLE
How to unit test brigade event handlers?

### ISSUE THREAD

**Issue by YaraMohammed** [Azure/brigade#506]
I have a `brigade.js` file which contains some events handlers right now I run `brig` command to trigger these events, Is there a way to have test cases to fire those events in NodeJS ?

**Comment by technosophos** [comment]
I've been toying around with this: https://github.com/technosophos/brigtest

**Comment by radu-matei** [comment]
Closing, but referenced this to be added in the docs.
Feel free to reopen if you have additional questions.

Thanks!
