### ISSUE TITLE
api(sorting): builds/jobs sort order is not chronological

### ISSUE THREAD

**Issue by flynnduism** [Azure/brigade#511]
Data displayed in Kashti appears in an odd sequence, and I think it's mapped to how the Brigade API is structured - sorting by the build ID hash. 

See example builds at: [https://example-api.technosophos.me/v1/project/brigade-9afa37b976ab4bd116557b613000959d24feb08dfac37fcf6ae3cb/builds](https://example-api.technosophos.me/v1/project/brigade-9afa37b976ab4bd116557b613000959d24feb08dfac37fcf6ae3cb/builds)

E.g. builds #1 and #5 were today, build #0 was yesterday. I would expect the output to be in a chronological order; though perhaps there is a reason for it being this way - I have a UI bias!

**Comment by flynnduism** [comment]
Related kashti issue [#179](https://github.com/Azure/kashti/issues/179).

**Comment by flynnduism** [comment]
You can see the unusual ordering in the API and also here in [Kashti](https://azure.github.io/kashti/#!/project/brigade-f1ccf2ad3495a1c68b82c78789061036240a9eb5ea2f0b0c4c20f9).

**Comment by technosophos** [comment]
Closed by #526
