### ISSUE TITLE
Make storage\cache mount points configurable

### ISSUE THREAD

**Issue by TimJones** [Azure/brigade#515]
It would be very helpful to for Job build storage\cache to have a configurable `path`, rather than the hard-coded private settings as current.

* `cp -a` from storage\cache to build dir will usually be slow (depends on your PVC config)
* `ln -s` won't work for a docker build (docker context doesn't follow symlinks)
* `ln -s` (in my specific case) is 'detected' by `php compose install` and therefore all vendoring library paths are hard-coded to the storage\cache directory

**Comment by technosophos** [comment]
I am imagining that we could do this on the `Job` objects pretty easily.

**Comment by TimJones** [comment]
💯 Awesome work!!
Thanks!!
