### ISSUE TITLE
vcs-sidecar not cloning the github repository in brigade-worker pod

### ISSUE THREAD

**Issue by disha94** [Azure/brigade#519]
Hi All,
I recently started using brigade. I have a requirement to use github repo code in brigade-worker pod , 
and according to the documentation, https://github.com/Azure/brigade/blob/a1c272cdbdeada3ec9e9ff910d21c7535a3255a8/docs/topics/values.md
looks like "vcs-sidecar" should be doing that. But when I exec into the worker pod, I see the "/vcs" is empty and there is not source code present in brigade worker pod.

I am using "vcsSidecar: "deis/git-sidecar:v0.14.0" in my projects.yaml file but I am still facing this issue.
Could someone please help me with the same.

**Comment by bacongobbler** [comment]
pointed out in Slack:

> I guess this is the issue,

> https://github.com/Azure/brigade/blob/v0.14.0/brigade-controller/cmd/brigade-controller/controller/handler.go#L136

> github gateway is creating the secret with script either from defaultscript or from the repo's code. And the validation here will return the pod spec because the script is not empty.

closing!
