### ISSUE TITLE
brigadier

### ISSUE THREAD

**Issue by Strandedpirate** [Azure/brigade#520]
Where is the brigadier npm package that is associated with this project?

I originally install this one but looking closer it years old and doesn't seem to have anything to do with brigade.
https://github.com/chge/brigadier

**Comment by technosophos** [comment]
We haven't fully packaged it into NPM yet. It's entirely in the source code base here. I started toying around with separating it into a facade. That work is here: https://github.com/technosophos/brigtest. If you can give us some use cases, it might help us figure out how to slice this library up in the right way.

**Comment by Strandedpirate** [comment]
An official package would allow static type checking with either Typescript or babel.js and a better dev time experience in whatever IDE I'm using by seeing the available properties/methods on each object without having to constantly lookup the documentation.

**Comment by technosophos** [comment]
Good point. And we'd like to add better support to VS Code, so this would help there.

**Comment by technosophos** [comment]
I'm experimenting with this idea. If we do it well, it would make VS Code extensions and unit tests much easier to write, as well.

**Comment by technosophos** [comment]
I'm experimenting with this idea. If we do it well, it would make VS Code extensions and unit tests much easier to write, as well.

**Comment by kooba** [comment]
I wonder what's the status on packaging `brigadier` as npm package. I can see effort started here https://github.com/Azure/brigade/pull/585 and here [@azure/brigadier](https://www.npmjs.com/package/@azure/brigadier) but no updates were made for a while. We would like to use Typescript to write our `brigade.js` files but reference to the npm package would need to be added to worker's dependencies list to build our `brigade.ts` file on worker start.

**Comment by technosophos** [comment]
I still plan on getting that finished. Currently, I'm in a rush to get a few other things done in time for KubeCon NA. But as soon as those are wrapped up, I'll finish this.

**Comment by radu-matei** [comment]
You can find the package on npm - https://www.npmjs.com/package/@azure/brigadier

Closing, but feel free to reopen if you have additional questions.
Thanks!
