### ISSUE TITLE
lag time in pod creation

### ISSUE THREAD

**Issue by Strandedpirate** [Azure/brigade#521]
There is on average a 1 minute delay between when brigade records an incoming request as a secret and the actual creation of the pod associated with it. I've seen 3 minute delays as well. 

Is there a setting that I can use in the chart to lower this to a specific number of seconds?

**Comment by technosophos** [comment]
Setting the pull policy on a worker to IfNotPresent might help. I _think_ the default is Always, which means it will to a docker pull each time a worker spawns.

Another culprit may be the PVC being spun up. Some systems (like AzureFile) seem to be slower than others (like NFS).

If you happen to narrow down the cause, please let me know. We're just starting to look at performance as we begin to focus on the 1.0.0 feature set.

**Comment by justindavies** [comment]
Seeing this on a new AKS cluster, I can see the push event in the GitHub GW pretty much instantly, and then there can be anything up to a 5/10 minute wait before the controller adds the job to the workqueue.  Tried downgrading to 0.13.1 as this worked perfectly on a different AKS cluster a month or so ago.  Will continue to investigate and feedback, but at the moment I'm seeing a slowdown between GW->CTRL

**Comment by technosophos** [comment]
On thing that would he helpful for testing is to see how long it is taking Kubernetes to notify Brigade. Running this command will start a watch:

```
$ kubectl get -w secret -l component=build
```

Once running that command, we should figure out how long it's taking for a `brig run` to show up on the watch list in `kubectl`. That should help us narrow down whether the problem is in the controller, or whether we're seeing unexpected delays on the API.

**Comment by justindavies** [comment]
Just tested this, I ran the watch, initiated a push, and it turned up within a couple of seconds.

➜  myapp kubectl get -w secret -l component=build
NAME                                        TYPE               DATA      AGE
brigade-worker-01cjhjbk4h0pg6kmakqhgjcss4   brigade.sh/build   10        3h
brigade-worker-01cjhzbkjtpn82vzfdgqqaz0fn   brigade.sh/build   10        1s

**Comment by technosophos** [comment]
And it took a few minutes for Brigade to start the worker?

**Comment by justindavies** [comment]
Yes, I saw the secret updated within a couple of seconds, worker took a few minutes more to spin up

**Comment by Strandedpirate** [comment]
My test results with varying options. My AKS master(s) are in a "degraded" state at the moment, for back of a better term, so these numbers would be different if ran a second time.

Worker `pullpolicy: Always` in project yaml, `imageForcePull` not set (defaults to false):
```
+-----------+----------------+
|  time     |     event      |
+-----------+----------------+
| 2:27:08pm | git checkin    |
| 2:27:43pm | worker started |
| 2:32:12pm | job started    |
+-----------+----------------+
```

Worker `pullpolicy: IfNotPresent` in project yaml, `imageForcePull` not set (defaults to false):
```
+-----------+----------------+
|  time     |     event      |
+-----------+----------------+
| 2:20:20pm | git checkin    |
| 2:21:01pm | worker started |
| 2:24:37pm | job started    |
+-----------+----------------+
```

Worker `pullpolicy: IfNotPresent` in project yaml, `imageForcePull` set to false:
```
+-----------+----------------+
|  time     |     event      |
+-----------+----------------+
| 2:13:47pm | git checkin    |
| 2:14:02pm | worker started |
| 2:15:30pm | job started    |
+-----------+----------------+
```

I'm running on AKS as well and the masters appear to be all running on over-provisioned hardware. e.g.  looks like they are packing too many masters on the same physical hardware. If so then that is playing a huge role in the lag times seen here. I can't get any straight answers on how to troubleshoot masters in AKS. I had an outage a month ago for the cluster I'm running brigade on that lasted ~30 hours with no way to find what the problem was. All the normal stuff I would do on an ACS cluster to troubleshoot or bring the master back only won't work on AKS because we have no control. The cluster eventually just came back online by itself.

By chance does anyone know how many masters you get with a new AKS? 1, 3 or 5?

**Comment by technosophos** [comment]
We have asked the AKS team to look into latency on `watch`. I'll update here if I hear anything. In the mean time, we're still looking for anything in the controller that might cause it to delay starting a worker.

**Comment by Strandedpirate** [comment]
Thanks, for now setting the worker `pullpolicy: IfNotPresent` in project yaml and `imageForcePull` set to false for the jobs is working much better for me. On average the worker pod starts up within ~10 seconds of the git commit which is perfect.

This event pipeline helps visualize why things may take a while from then on depending on image pull policies, size of images, and size of vcs repository.
`secret written -> worker starts (worker image pulled locally vs remote, sidecar always pulled?) -> git sidecar pulls code-base (*depends on project setup) -> custom code execution -> job(s) start (image(s) pulled locally vs remote)`

Also, it looks like `buildStorageSize` is hard-coded to `50Mi` and not honoring the project yaml? Remains to be seen, but this could potentially further reduce startup times if I could set it to half that.

https://github.com/Azure/brigade/blob/master/pkg/storage/kube/project.go#L157

**Comment by technosophos** [comment]
@Strandedpirate I think that line of code is working correctly, but I'll test it. `def(string, string)` is supposed to return the first string if it's not empty, or else return the second string.

**Comment by technosophos** [comment]
In my Minikube cluster, I just verified that setting `buildStorageSize` to 10Mi resulted in PVCs that were 10Mi instead of 20Mi:

```console
$ kubectl  get pvc --n brigade
NAME                                        STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
brigade-worker-01cjncmwgpznfh54asz8fwdhb0   Bound     pvc-9891b9d1-8a21-11e8-ad79-080027526bb1   10Mi       RWX            standard       2s
github-com-technosophos-zolver-three        Bound     pvc-e6efe780-8a20-11e8-ad79-080027526bb1   5Mi        RWX            standard       5m
```

If you are seeing something different, can you add a new issue and I'll track down the problem? Thanks.

**Comment by Strandedpirate** [comment]
Awesome thanks for all the help!
