### ISSUE TITLE
Monitoring a brigade job after brig run

### ISSUE THREAD

**Issue by vaibhavpals** [Azure/brigade#530]
We have been evaluating Brigade for our systems. 
But is there a recommended approach for using the 'brig run' cli? 

From what i have observed, the 'brig run' command sends a file into the cluster and waits for it to complete.
What we want to do is trigger a brig run, get the build id and then monitor the job through another application using the brigade-api. 
Is there a recommended way to just get the build id and not let it wait for the build to complete as some of the builds are very long running?

**Comment by technosophos** [comment]
I'll consider this a feature request! I think I even had code written for this, but never committed it.
