### ISSUE TITLE
release assets for brig missing in 0.13.1 and 0.15.0

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#533]
[According to brigade.js](https://github.com/Azure/brigade/blob/28a4e8afa3172800b4b810db41cd6412c3c94179/brigade.js#L93-L106), this is where the release assets should be stored, but it doesn't look like they were published in those releases.

Reason being is that I'm trying to update the [fish food for brig](https://github.com/fishworks/fish-food/blob/master/Food/brig.lua), but there's no release to deploy :joy:

**Comment by technosophos** [comment]
I ran `brig run` to generate the 0.15 binaries, but I need to fix the main brigade script to do that automatically. Marking this as a bug.
