### ISSUE TITLE
Kashti's deployment/pod should proxy API traffic to the internal API server

### ISSUE THREAD

**Issue by technosophos** [Azure/brigade#535]
Right now, Kashti is served from one pod, and the API runs in a different one. This is for historical reasons, but should be fixed as we merge Kashti into Brigade.

The fix would be to have Kashti's nginx server proxy API traffic into the cluster. This would have the additional benefit of giving us a central place to configure AuthN.

**Comment by radu-matei** [comment]
This would also allow us not to start and manage two tunnels when using `brig dashboard`.

**Comment by technosophos** [comment]
Yeah, it would simplify that very nicely!

**Comment by radu-matei** [comment]
Implemented in https://github.com/Azure/kashti/pull/187
