### ISSUE TITLE
Any work on VSTS gateway

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Azure/brigade#542]
Just started looking at Brigade.  Wondering if anybody has started in on a VTFS gateway?

**Comment by technosophos** [comment]
As far as I know, nobody has seriously started on this.

**Comment by radu-matei** [comment]
Hey @MatthewDavidCampbell!
I assume you're referring to VSTS / TFS?

Apart from source control events, what other events are you interested in?
Things like a build started / finished, a new release - could you please describe your use case?

Thanks!

**Comment by MatthewDavidCampbell** [comment]
@radu-matei Came across Brigade by accident but like the idea behind it.  Use VSTS (misspell) at work.  Looking mainly for source control events (similar to what is done with the Git gateway).

**Comment by technosophos** [comment]
I am fairly sure VSTS has a webhook mechanism, so we could certainly produce something similar to the GH gateway.

**Comment by MatthewDavidCampbell** [comment]
VSTS [webhooks](https://docs.microsoft.com/en-us/vsts/service-hooks/services/webhooks?view=vsts).  Guess the implementation would be very similar to that with GitHub.  Is a VSTS gateway something you'll want in the Brigade repo or as a reference (like the related projects e.g. *GitLab events*)?

**Comment by radu-matei** [comment]
Hey, @MatthewDavidCampbell!
Have a look at https://github.com/radu-matei/brigade-vsts-gateway - it sends events coming from VSTS webhooks into Brigade pipelines.

Let us know of any feedback you might have.

**Comment by MatthewDavidCampbell** [comment]
@radu-matei, Awesome. Maybe that project could be linked in with this one since Google didn’t uncover the VSTS gateway for me.

**Comment by radu-matei** [comment]
Yeah, you couldn't find it when you opened the issue because it didn't exist, I built it last week :)
But yes, adding it to the list of related projects and gateways sounds like a good idea.
