### ISSUE TITLE
cant deploy job in another namespace

### ISSUE THREAD

**Issue by ARMUGHAN-SHAHID** [Azure/brigade#543]
I edited the namespace field in the values.yaml file used for creating project
after installing the project no pod for a job is being created in the new namespace or default namespace.

Currently my brigade-project secret is in agent-namespace
and brigade ctr and brigade api pods are running in default namespace .
Please guide me where i am doing something wrong.

**Comment by technosophos** [comment]
At the moment, we are only supporting running all of Brigade in one namespace. So project config, worker, and job pods are all in the same namespace. Hopefully, we will be able to make this more flexible in the future. But for now, this is the only way to run Brigade.
