### ISSUE TITLE
Releases for brig cli for Windows lacking .exe extension

### ISSUE THREAD

**Issue by LittleColin** [Azure/brigade#547]
Downloading **brig-windows-amd64** from the releases page at: https://github.com/Azure/brigade/releases

This gives a file without any extension but is actually a .exe file. Renaming to brig.exe and putting it in path then makes it work but I've not seen this mentioned in the readme.

**Comment by LittleColin** [comment]
Ah now I realise the problem, I've now spotted the following in release 0.15:
https://github.com/Azure/brigade/pull/478

Ironically release 0.15.0 which contains this fix doesn't have the associated windows binary asset attached.

**Comment by LittleColin** [comment]
It looks like the push is assuming the source file also has the .exe extension but presumably the intention was only the destination should have .exe added.

`cx.tasks.push(`github-release upload -f ./bin/${name} -n ${name} -t ${tag}`)  `

**Comment by technosophos** [comment]
@LittleColin Oh, yes -- your suggestion would fix it.

**Comment by LittleColin** [comment]
Seems we've lost the .exe extension for brig in v0.18.0 (previous two versions had the .exe extension)

**Comment by blimmer** [comment]
Have we ever considered using go-releaser? https://github.com/goreleaser/goreleaser

**Comment by bacongobbler** [comment]
that's neat! We're using [github-release](https://github.com/Azure/brigade/blob/ba8f4fd8c65d9398aa4ca98c4433e61c752b28aa/brigade.js#L113) in the CI pipeline which is a subset of goreleaser's features.

**Comment by vdice** [comment]
@LittleColin apologies for the hiccup (see https://github.com/Azure/brigade/issues/659#issuecomment-429423155).   Windows binary now up with proper `.exe` extension [here](https://github.com/Azure/brigade/releases/download/v0.18.0/brig-windows-amd64.exe).  Thank you!
