### ISSUE TITLE
"imagePullSecrets" for private registry not working

### ISSUE THREAD

**Issue by emmayang** [Azure/brigade#566]
Hi,

I have a private docker registry, and put some of my images in there. And I followed the [Kube official document ](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) about how to add a secret in the cluster, and reference that secret in the project values.yaml file. 

However it's somehow not working for me, and I double confirmed the credential to login to my private docker registry is correct. Here are some information (I removed my project related information):

---------------------
project helm status, and you can see the secret `regcred` is set to my brigade project 
```
root:~#: helm get istio-cicd
2018/07/21 00:03:45 warning: skipped value for github: Not a table.
REVISION: 1
RELEASED: Fri Jul 20 15:45:24 2018
CHART: brigade-project-0.15.0
USER-SUPPLIED VALUES:
allowPrivilegedJobs: "true"
cloneURL: https://github.XXXX.com/XXX/XXX.git
github:
  baseURL: https://github.XXXX.com/XXX/XXX
  token: 7af1d1186a18059a2d092c3419e16af25c035b2e
  uploadURL: https://github.XXXX.com/XXX/XXX
imagePullSecrets: regcred
kubernetes: null
project: XXXX/brigade
repository: github.XXXX.com/XXXX/brigade
secrets: null
sharedSecret: <SuperSecret>
vcsSidecar: deis/git-sidecar:latest
worker: null

COMPUTED VALUES:
allowPrivilegedJobs: "true"
cloneURL: https://github.XXXX.com/XXX/XXX.git
github:
  baseURL: https://github.XXXX.com/XXX/XXX
  token: 7af1d1186a18059a2d092c3419e16af25c035b2e
  uploadURL: https://github.XXXX.com/XXX/XXX
imagePullSecrets: regcred
project: XXXX/brigade
repository: https://github.XXXX.com/XXX/XXX
sharedSecret: <SuperSecret>
vcsSidecar: deis/git-sidecar:latest
```

Could you please shed some light on this? Or any guidance about how to further debug this? 

And one another question, is where this secret is attached? l'm asking because I'd like to track it down in `brigade-worker-XXX` pod, and confirm the secret is correctly attached to it.

**Comment by technosophos** [comment]
For the second question: If you run a brigade build, it will give you a build ID, which will spawn a worker. That worker (`brigade-worker-XXXX`) will have the image pull secret on it. You can do `kubectl get po -l component=build` to see a list of those. You can also get the build IDs directly with `brig build list`.

To get the job pods, you can do `kubectl get po -l component=job` to get a list of jobs. And if you know the build ID, you can do `kubectl get po -o yaml -l component=job,build=01ck4qk22qwbd5ect3y20s0b7t` and get all the jobs for that build.

The pods for workers and jobs will hang around for a while after completion. So you don't have to worry about running these commands right when the build goes.

Okay, with all of that in mind, to debug I would recommend:

- Use `brig run` (if possible) to trigger a new build. That will stream the logs and give you a build ID.
- When the build fails, find the Job pod that should have had the imagePullSecrets on it, and see if it is there.

If it's not there, then we'll have to figure out how it got lost along the way. It's probably a bug in Brigade at that point.

If it is there, then the next step would be to deploy a basic pod that just grabs that image with that image pull secret, and see if the image pull secret works in isolation of the rest of Brigade.

Please let me know what you find out, and we can go from there.

**Comment by emmayang** [comment]
@technosophos sorry for the late response... 
I followed the steps you suggested, re-trigger the job and check pod definition, and found the output is empty.

Here's the job execution log: 
```
Started build 01ckk3f6y3v2vpbpnqac0zy7nq as "brigade-worker-01ckk3f6y3v2vpbpnqac0zy7nq"
installing moment@2.22.2
installing underscore@1.9.1
prestart: src/brigade.js written
[brigade] brigade-worker version: 0.15.0
[brigade:k8s] Creating PVC named brigade-worker-01ckk3f6y3v2vpbpnqac0zy7nq
[brigade:k8s] looking up utils/github-XXXXXXX-build-src
[brigade:k8s] Creating secret build-src-01ckk3f6y3v2vpbpnqac0zy7nq
[brigade:k8s] Creating pod build-src-01ckk3f6y3v2vpbpnqac0zy7nq
[brigade:k8s] Timeout set at 900000
[brigade:k8s] utils/build-src-01ckk3f6y3v2vpbpnqac0zy7nq phase Pending
  Error: rpc error: code = Unknown desc = Error response from daemon: repository   emmayangy/istio-base not found: does not exist or no pull access

done
  - k8s.js:430 k.readNamespacedPod.then.response
    ./dist/k8s.js:430:36


[brigade:app]   Error: job build-src(build-src-01ckk3f6y3v2vpbpnqac0zy7nq): Error: rpc error:   code = Unknown desc = Error response from daemon: repository emmayangy/istio-b  ase not found: does not exist or no pull access

  - brigadier.js:56 jr.run.catch.err
    ./dist/brigadier.js:56:35


  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7


[Istio] **** Error occured in scripts
[brigade:app] error handler is cleaning up
[brigade:k8s] Destroying PVC named brigade-worker-01ckk3f6y3v2vpbpnqac0zy7nq
error Command failed with exit code 1.
```

And the job ID is `01ckk3f6y3v2vpbpnqac0zy7nq`, and then I got the pod definition:
```
brigade:$ kubectl get po -o yaml -l component=job,build=01ckk3f6y3v2vpbpnqac0zy7nq
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

And the pod definition is empty, and secret is not there.

**Comment by technosophos** [comment]
Ah! I think I had misunderstood which image you were trying to pull. I thought you had a custom worker. My mistake.

If you want to allow a job to use an image pull secret, you need to pass the names of the image pull secrets in the `Job` definition in JS:

```
events.on("exec", (e, p) => {
  let j = new Job("example", "emmayangy/istio-base);
  j.imagePullSecrets = ["my-secret"];
})
```

https://github.com/Azure/brigade/blob/master/docs/topics/javascript.md#the-job-class

We did it this way to prevent jobs from automatically inheriting security capabilities simply because the parent worker had them.

Let me know if that fixes it. Oh, and thanks for tracking down #576. I merged the fix for it today.

**Comment by emmayang** [comment]
@technosophos Thanks for your reply! And I actually have both customized worker and job image, and the credential for job image worked now, thanks again.

**Comment by technosophos** [comment]
Okay. I'll mark this as resolved. Thanks!

**Comment by tomfotherby** [comment]
Thanks for this GitHub Issue, I found it useful.

My problem was that my registry secret was not in the `brigade` namespace. My error was:

```
$ brig run myproject
...
[  Error: rpc error: code = Unknown desc = Error response from daemon: pull access denied for myorg/kubectl, repository does not exist or may require '  docker login': denied: requested access to the resource is denied
...
```

and I fixed it by adding `-nbrigade` to the `kubectl create secret docker-registry` command:

```
# Created a docker-registry secret IN THE BRIGADE NAMESPACE
$ kubectl create secret -nbrigade docker-registry brigade-docker-login --docker-email="sre@example.com" --docker-password="redacted" --docker-username=redacted
