### ISSUE TITLE
RBAC on minikube 22.2 fails: "cannot list secrets in the namespace" for default

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#57]
<a href="https://github.com/squillace"><img src="https://avatars0.githubusercontent.com/u/1422718?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [squillace](https://github.com/squillace)**
_2017-09-27 22:49:58_

----

Situation: 
1. minikube .22.2
2. Ubuntu 17.04
3. helm 2.5.1
4. minikube using kvm, started with: `minikube start --vm-driver kvm --extra-config=apiserver.Authorization.Mode=RBAC` to enable rbac. 
5. Helm given clusteradmin role to oversee the cluster.
6. acid .2 installed from project repo chart: `helm install chart/acid --name acid`
7. acid project installed: `helm install acid-project -f ~/work/nogo/slacid/empty-testbed.yaml --name squillace-demo`
8. lsd invokes the project: `acid git:(master) ✗ ./bin/lsd --file $HOME/work/nogo/slacid/acid.js squillace/slacid`

Result: 
```
Started acid-worker-01bv2qw5792bt1bwgsj2wty6rm-master
lsd [-f FILE] PROJECT_NAME
pods "acid-worker-01bv2qw5792bt1bwgsj2wty6rm-master" not found
```

Logs of the controller pod:

```
E0927 22:40:34.227352       5 reflector.go:201] github.com/deis/acid/acid-controller/cmd/acid-controller/controller/controller.go:122: Failed to list *v1.Secret: User "system:serviceaccount:default:default" cannot list secrets in the namespace "default". (get secrets)
```

if installed into kube-system, the worker pod is created in the default namespace, not kube-system, so there's some hard-coding in there making assumptions about where the pod is created.

**Comment by bacongobbler** [comment]
**Comment by [squillace](https://github.com/squillace)**
_2017-09-28 00:20:23_

----

confirmed that in an ACS cluster without RBAC on, ACID job succeeds quite well.

**Comment by bleggett** [comment]
I'm seeing a similar issue with Tectonic (which uses RBAC). Why was this closed? Is RBAC support not planned? Or is RBAC supported, and I'm seeing a different issue?

**Comment by bacongobbler** [comment]
RBAC is supported. You can enable RBAC support when installing brigade by using the `--set rbac.enabled=true` flag. More info at https://github.com/Azure/brigade/blob/master/docs/topics/security.md

Does that help answer your question? :)

**Comment by bleggett** [comment]
AH! Thanks. Missed that doc :D
