### ISSUE TITLE
Send email notifications with brigade

### ISSUE THREAD

**Issue by disha94** [Azure/brigade#570]
Currently, I can see their is an integration with brigade and slack to send notifications.
Is there any such integration with gmail, using which we can emails for brigade deployment pipelines?

**Comment by radu-matei** [comment]
Hey, @disha94!
You can find the full implementation of the Slack notifier here - https://github.com/technosophos/slack-notify

Essentially, if you can build a container that uses either a CLI or library that connects to Gmail (with any private tokens and email addresses as project secrets), then it is entirely possible.

**Comment by dgkanatsios** [comment]
You could probably use [this](
https://github.com/namshi/docker-smtp) container to relay emails to Gmail from inside a Brigade build

**Comment by radu-matei** [comment]
Closing, but feel free to reopen if you have additional questions.

Thanks!
