### ISSUE TITLE
brig dashboard results in broken pipe and timeout

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#587]
Recently upgraded my AKS cluster to v1.10.6 and started seeing a high rate of errors while using `brig dashboard`, which make using Kashti nearly impossible.

Since `brig` uses a similar way of port forwarding to Helm, this appears to be the same issue as in https://github.com/helm/helm/issues/3480

```
error copying from remote stream to local connection: readfrom tcp6 [::1]:8081->[::1]:52703: write tcp6 [::1]:8081->[::1]:52703: write: broken pipe

error creating forwarding stream for port 8081 -> 80: Timeout occurred
```

Need to figure out the root cause of the Helm issue, as well as if this is related to the AKS cluster upgrade.

**Comment by weinong** [comment]
@vdice we have a fix for that, would you like to try it out? send me your subscription.. :)

**Comment by vdice** [comment]
I'm not seeing this issue after receiving the patch from @weinong.  @radu-matei let's get the patch to you (or see if the fix is GA) and see if we can get confirmation.

**Comment by dgkanatsios** [comment]
Fix for the issue @vdice mentions has been deployed ([link](
https://azure.microsoft.com/en-us/updates/azure-kubernetes-service-december-update/)), is this error still happening?
