### ISSUE TITLE
brig project creatre does not generate sharedsecret

### ISSUE THREAD

**Issue by mattfarina** [Azure/brigade#597]
https://github.com/Azure/brigade/blob/8dad9088fddbb33505cdd710fef93e6b2d78c6e6/brig/cmd/brig/commands/project_create.go#L279-L282

So, when the shared secret is NOT empty it will generate one. And, per #574 there is no prompt to add one. So, `brig project create` does not provide a way to set a shared secret.

Since there is no way to update a project with brig (at least not an obvious one) it means we have to muck with k8s secrets to set one as an interim solution?

**Comment by technosophos** [comment]
Ugh... that is my fault. I'll fix that.
