### ISSUE TITLE
Project as K8s CRD type

### ISSUE THREAD

**Issue by alexei-led** [Azure/brigade#6]
It would be convenient, if **brigade project** could be defined as `CRD` resource and not as specially formatted `Secret`. You already have all components in-place: a controller that listens for K8s events and project logical entity with a set of fields.
Current implementation looks like a tricky "hack".

**Comment by technosophos** [comment]
We made the decision not to use CRDs until they were finalized, just in case another TPR-like fiasco happens.

**Comment by bacongobbler** [comment]
also related: https://github.com/kubernetes/helm/issues/1650

Additionally secrets have the added benefit of the ongoing work with [encrypting secret data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/). It's still in alpha, but GitHub tokens, webhook API keys/secrets etc. would benefit from this if we stuck to storing project configuration in a secret.

**Comment by technosophos** [comment]
Oh, yeah -- I forgot about the encryption part. Since projects store some fairly sensitive data (secrets, SSH keys, etc.), we do want the built-in encryption support.

**Comment by technosophos** [comment]
There's also the part about mounting secrets as volumes, which we do with projects. I documented these things earlier this week so that at least we can explain why we made the choices we did.
