### ISSUE TITLE
Missing example projects

### ISSUE THREAD

**Issue by noelo** [Azure/brigade#60]
In https://github.com/Azure/brigade/blob/master/docs/topics/design.md under High Level Flow the two example projects are not found 

github.com/technosophos/example

github.com/helm/otherexample

**Comment by bacongobbler** [comment]
Hey! I’m going to close this issue due to #3. It’s well known at this point that this document is out of date and needs a refresh. Let’s not that in #3 so we can track that progress. Thanks!
