### ISSUE TITLE
Should vacuum delete running workers?

### ISSUE THREAD

**Issue by cjhpaul** [Azure/brigade#604]
I realized vacuum deletes all brigade workers even if they are in the middle of doing something.
If this is intended behavior, then maybe we need to add a config variable to let users decide whether to delete them all regardless, or delete workers not in running/pending phase. I created the corresponding pull request regarding this (#603).

**Comment by technosophos** [comment]
It was intentional, but I think your proposal is correct -- we should make that behavior configurable.

**Comment by technosophos** [comment]
Closed via #603
