### ISSUE TITLE
Feature request: In the github gateway it would be nice if events could fire for issue and issue_comment

### ISSUE THREAD

**Issue by mattfarina** [Azure/brigade#605]
These events could be used to run scripts that do things like update labels on the issue. It would be useful for non-build automation.

**Comment by technosophos** [comment]
What should we set as the commit/reference for these? `refs/heads/master` or something like that?

**Comment by radu-matei** [comment]
Closing in favor of #550, but also added as a request for the docs.

Feel free to comment in #550, or reopen if these are separate requests.
Thanks!
