### ISSUE TITLE
kube lego deprecated

### ISSUE THREAD

**Issue by mattfarina** [Azure/brigade#607]
On the github page you note,

> You may optionally use the Kube LEGO Helm chart and set up an NGINX SSL proxy in front of your Brigade Gateway (brigade-gw) service.

Kube lego is deprecated and folks are now directed to use https://hub.kubeapps.com/charts/stable/cert-manager

Docs update?

**Comment by mattfarina** [comment]
There is documentation on using cert-manager that works (at least for me) at https://docs.microsoft.com/en-us/azure/aks/ingress

You could link to that.

**Comment by technosophos** [comment]
Is cert-manager considered non-experimental now? Our previous issue was that it was not working, while kube-lego was. But it looks like things are in better shape now.
