### ISSUE TITLE
Brigade Helm chart repo is not working

### ISSUE THREAD

**Issue by rimusz** [Azure/brigade#62]
```
$ helm repo add brigade https://azure.github.io/brigade
Error: Looks like "https://azure.github.io/brigade" is not a valid chart repository or cannot be reached: Failed to fetch https://azure.github.io/brigade/index.yaml : 404 Not Found
```

**Comment by aranair** [comment]
You could clone the repo and do `helm install --name brigade ./chart/brigade` instead.

**Comment by rimusz** [comment]
yup, I know that and using this way, just reported the issue, as some less knowledgeable users could stuck with that problem.

**Comment by bacongobbler** [comment]
Thanks for the report! It’s possible that GitHub pages has to be re-configured to serve these assets again after we moved from deis/brigade to Azure/brigade.

**Comment by bacongobbler** [comment]
this has been re-enabled and should now work. https://azure.github.io/brigade/index.yaml is being served.

**Comment by rimusz** [comment]
yup, all good now, thanks for fixing it @bacongobbler
