### ISSUE TITLE
tagged images?

### ISSUE THREAD

**Issue by mattfarina** [Azure/brigade#624]
The images brigade pulls are versioned at `:latest`. For example,

https://github.com/Azure/brigade/blob/9107208b4158faff7b2a127c854ff5b4e05f31a1/brigade-controller/cmd/brigade-controller/controller/controller_test.go#L27

This can create a whole host of problems. Can we get these versioned?

**Comment by technosophos** [comment]
Is this just in the test? I am pretty sure that by default this is controlled by the settings in the project.

**Comment by mattfarina** [comment]
Sorry for the bad pointer.

The vcs sidecar is set to `deis/git-sidecar:latest`. I looked in the secret to double check. This was created with the `brig` command but also shows up at:

https://github.com/Azure/brigade/blob/9107208b4158faff7b2a127c854ff5b4e05f31a1/charts/brigade-project/values.yaml#L84

**Comment by adamreese** [comment]
Looks like we take care of that in the template. https://github.com/Azure/brigade/blob/master/charts/brigade-project/templates/secret.yaml#L24-L31

#637 removes the :latest override
