### ISSUE TITLE
Unable to install brigade

### ISSUE THREAD

**Issue by pravalikam** [Azure/brigade#634]
**helm install -n brigade brigade/brigade**
Error: release brigade failed: namespaces "brigade" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "brigade"

**helm install -n brigade brigade/brigade --set rbac.enabled=false --set vacuum.enabled=false --set api.service.type=LoadBalancer --namespace=brigade**
Error: release brigade failed: namespaces "brigade" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "brigade"

**Comment by radu-matei** [comment]
Hey!
It appears you are on a cluster with [RBAC enabled](https://kubernetes.io/docs/reference/access-authn-authz/rbac/), so you want to pass the `--set rbac.enabled=true`, or modify the chart's `values.yaml` file.

Let me know if that works and if you have additional questions.

**Comment by pravalikam** [comment]
I tried it not working. still getting the same error

**Comment by bacongobbler** [comment]
When you installed Helm, did you apply the correct RBAC policies? Looks like Helm can't install resources in the `brigade` namespace because the service account bound to tiller doesn't have the right permissions to install into that namespace. See https://docs.helm.sh/using_helm/#role-based-access-control for more info

**Comment by pravalikam** [comment]
I am new to this field. Can you please help me out with details.

**Comment by bacongobbler** [comment]
OK, let's start from scratch. From a brand new cluster, run the following:

```
$ echo << EOF > tiller-rbac-config.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF
```

Then:

```
$ kubectl create -f rbac-config.yaml
serviceaccount "tiller" created
clusterrolebinding "tiller" created
$ helm init --service-account tiller
```

Once that's done, you should be able to install brigade using

```
helm install -n brigade brigade/brigade --set rbac.enabled=true --set vacuum.enabled=false --set api.service.type=LoadBalancer --namespace=brigade
```

Let us know if you run into further trouble.

**Comment by pravalikam** [comment]
still getting the same error

**Comment by bacongobbler** [comment]
Okay. It would be really helpful if you could please provide the steps you used, from how you provisioned a kubernetes cluster, to what version of helm you're running, and the steps you used to install brigade. That way we can try to go through the same steps and try to reproduce the issue you're seeing. Thanks!

**Comment by pravalikam** [comment]
**I used this yaml file to generate Kubernetes cluster and Helm**

set -ex
# Prevent Docker from ruining iptables policy on FORWARD
mkdir /etc/systemd/system/docker.service.d
cat << EOF > /etc/systemd/system/docker.service.d/noiptables.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --iptables=false
EOF
if [ "$proxy_host" ]; then
  cat << EOF > /etc/systemd/system/docker.service.d/proxy.conf
[Service]
Environment="HTTP_PROXY=http://$proxy_host:$proxy_port"
Environment="HTTPS_PROXY=http://$proxy_host:$proxy_port"
EOF
fi
systemctl daemon-reload
# Install docker
apt-get install -y docker-engine=17.05.0~ce-0~ubuntu-xenial
# Install all kube binaries
docker run --rm mirantisworkloads/kube-binaries:v1.8.7 cat /package.cpio.bz2 | bunzip2 | cpio -i
# Configure kubelet to use pause image from Docker Hub
cat > /etc/systemd/system/kubelet.service.d/20-pod-infra-image.conf <<EOF
[Service]
Environment="KUBELET_EXTRA_ARGS=--pod-infra-container-image=mirantisworkloads/pause-amd64:3.0"
EOF
systemctl daemon-reload
systemctl restart kubelet
# Run kubeadm
cat << EOF > /root/kubeadm.yaml
apiServerCertSANs:
- $floatingip
imageRepository: mirantisworkloads
token: $token
unifiedControlPlaneImage: mirantisworkloads/hyperkube-amd64:v1.8.7
kubernetesVersion: v1.8.7
EOF
modprobe br_netfilter
kubeadm init --config /root/kubeadm.yaml
# Copy kubeconfig to ubuntu user
mkdir -p ~ubuntu/.kube
cp /etc/kubernetes/admin.conf ~ubuntu/.kube/config
chown -R ubuntu:ubuntu ~ubuntu/.kube
# Install Calico and Tiller
export KUBECONFIG=/etc/kubernetes/admin.conf
until kubectl get nodes; do
  sleep 2
doneexport KUBECONFIG=/etc/kubernetes/admin.conf
until kubectl get nodes; do
  sleep 2
done
kubectl apply -f /root/calico.yaml
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
helm init --service-account default

**Comment by bacongobbler** [comment]
>     * helm init --service-account default

Did you apply the changes mentioned in https://github.com/Azure/brigade/issues/634#issuecomment-422896249? It doesn't look like that's been reflected in this script.

**Comment by bacongobbler** [comment]
Check the output of `kubectl -n kube-system get pods` and see what state Tiller's in.

**Comment by pravalikam** [comment]
Thanks for the help. its working now
