### ISSUE TITLE
Brigade not updating the github on pull_request failure or success builds

### ISSUE THREAD

**Issue by tamizharasanr** [Azure/brigade#635]
Jobs are successfully triggered on every event of GitHub. But whenever the pull-request fails or succeeds, it won't get notified in the GitHub pull-request page. I just follow the tutorial of the brigade docs.

As per the docs, pull request has the checks with success and failure event.
![image](https://user-images.githubusercontent.com/43002189/45948654-8223d500-c016-11e8-84a9-4c79ba3e5d8e.png)

I got the brigade containers up and running, jobs are getting triggered and in kashti dashboard, I can see the result. I just wonder what I am missing here.

**Comment by adamreese** [comment]
You probably need to add a notification step to your build.  This is an example from the brigade repo https://github.com/Azure/brigade/blob/master/brigade.js#L122-L134 https://github.com/Azure/brigade/blob/master/brigade.js#L52

**Comment by tamizharasanr** [comment]
It's working perfectly when I used as in the above file. 
The issue here is no reference for the github-notify project in the getting started guide ( https://azure.github.io/brigade/intro/ ). 
It will be better if the reference added to the guide so that there won't be any issues related to the notification.

**Comment by radu-matei** [comment]
Considering that this is the `brigade.js` file in the doc:

```javascript
const { events, Job } = require("brigadier");

events.on("push", function(e, project) {
  console.log("received push for commit " + e.commit)

  // Create a new job
  var node = new Job("test-runner")

  // We want our job to run the stock Docker Python 3 image
  node.image = "python:3"

  // Now we want it to run these commands in order:
  node.tasks = [
    "cd /src/app",
    "pip install -r requirements.txt",
    "cd /src/",
    "python setup.py test"
  ]

  // We're done configuring, so we run the job
  node.run()
})
```

And at the end there's this message:

> Assuming all is set up, you should see a shiny green checkmark next to your commit.

We should wither:
- add the notification part in the `brigade.js` file
or
- remove the part with the shiny green checkmark from the doc

**Comment by rosstimson** [comment]
Just spent a while looking into why this wasn't working after following the guide.  I'd love to see the guide updated with a simple example for sending GH notifications, there is a lot going on in the one from the brigade repo referenced above.
