### ISSUE TITLE
brigade project not associated with a git repository

### ISSUE THREAD

**Issue by vincentzhou2013** [Azure/brigade#636]
It looks like the only way currently available is to send the script with the event every time it's emitted (#250 ). Is there any other way, like if VCS repository is empty, fall back to default brigade script which is uploaded when the project is created? Thanks.

**Comment by radu-matei** [comment]
Hey, @vincentzhou2013!
Have a look at the Helm values file for Brigade - https://github.com/Azure/brigade/blob/master/charts/brigade-project/values.yaml#L23

There is a `defaultScriptName` field where you can have your script as Kubernetes ConfigMap:

```
# OPTIONAL: defaultScriptName is the name of a configmap used as a fallback brigade.js.
# defaultScriptName: default-script-cm
```

Let us know if you have additional questions!

**Comment by vincentzhou2013** [comment]
Thanks! if repository is empty (asked when creating the brigade project),  will it automatically fallback to this default? I don't want it to throw exceptions when repository setting is empty. Thanks.

**Comment by zoidbergwill** [comment]
That's what it sounds like from the documentation.

**Comment by vincentzhou2013** [comment]
won't work. the vcs-sidecar always tries to pull source code from the repository specified when the project is created. if no valid repository available, the worker pod just fails (Init:Error) . Even after I disabled the vcs-sidecar by manually editing project secret's vcs-sidercar value to null, brigade-worker (version: 0.17.0) was able to start, but quickly ran into error.
`[brigade:app]   TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or arr  ay-like object.
  
  - k8s.js:601 b64dec
    ./dist/k8s.js:601:19
  
  - k8s.js:627 secretToProject
    ./dist/k8s.js:627:15
  
  - k8s.js:124 defaultClient.readNamespacedSecret.catch.then.result
    ./dist/k8s.js:124:16
  

[brigade:app] error handler is cleaning up
/home/src/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

  TypeError: Cannot read property 'log' of undefined
  
  - k8s.js:78 BuildStorage.destroy
    ./dist/k8s.js:78:21
  
  - app.js:65 destroyStorage
    ./dist/app.js:65:18
  
  - app.js:82 EventRegistry.brigadier.events.once
    ./dist/app.js:82:17
  
  - events.js:81 EventRegistry.fire
    ./dist/events.js:81:14
  
  - brigadier.js:34 Object.fire
    ./dist/brigadier.js:34:20
  
  - app.js:185 App.fireError
    ./dist/app.js:185:19
  
  - app.js:103 process.on
    ./dist/app.js:103:18
`

**Comment by vincentzhou2013** [comment]
#272 suggested a solution.

**Comment by vincentzhou2013** [comment]
It works with a custom vcs-sidecar ( null git pull ). but even without a repository, a repository name is still needed. null value will trigger above exception. 
Suggestion:  "brig project create" should provide a path for projects not having repositories.
