### ISSUE TITLE
Unable to install brig cli

### ISSUE THREAD

**Issue by thezaa** [Azure/brigade#645]
**make bootstrap brig**

gives this error

make: Nothing to be done for 'bootstrap'.
go build -ldflags ' -X github.com/Azure/brigade/pkg/version.Version=v0.17.0-37-gd6f2a59' -o bin/brig ./brig/cmd/brig
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:20:2: cannot find package "context" in any of:
        /root/go/src/github.com/Azure/brigade/vendor/context (vendor tree)
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /root/go/src/context (from $GOPATH)
Makefile:25: recipe for target 'brig' failed
make: *** [brig] Error 1

**Comment by thezaa** [comment]
****I installed Go 1.11**

**and now if do : Brig version**

this is the error
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at brig.BRIGconsole.<init>(BRIGconsole.java:34)
        at brig.Main.main(Main.java:26)

**Comment by bacongobbler** [comment]
that doesn't seem like brigade. Looks more like an issue with the java app running `brig version`, so I'm not sure if I can help you there. What project is this?

What if you run `brig version` straight from the terminal?

**Comment by radu-matei** [comment]
@thezaa - the project that you seem to run here is https://github.com/happykhan/BRIG

**Comment by thezaa** [comment]
@radu-matei 


So do i Installed it wrong

**Comment by radu-matei** [comment]
Yeah, you are simply trying to run a completely different, unrelated project.

To install `brig`, which is the command line tool for the Brigade project (https://azure.github.io/brigade/):

>To build Brig, clone the Brigade repository to $GOPATH/src/github.com/Azure/brigade and then run make bootstrap brig.
> If you have $GOPATH issues, you may need to add the Brigade binary to your path.

Let us know if this is the project you are trying to build and if you have issues in doing so.

**Comment by radu-matei** [comment]
Ok, now do you have a `bin` directory? Is there anything inside?
If the building succeeded, there should be a `brig` binary there.

**Comment by thezaa** [comment]
I dont find brig in the bin directory

**Comment by thezaa** [comment]
i see brig in $GOPATH/bin

**Comment by thezaa** [comment]
> Ok - how about @bacongobbler's comment earlier - [#645 (comment)](https://github.com/Azure/brigade/issues/645#issuecomment-426084230)
> 
> Do you still see the errors above? If yes, then you might have to update Go.

No

**Comment by thezaa** [comment]
@radu-matei I see brig in $GOPATH/bin

**Comment by radu-matei** [comment]
Ok - now if you:

- execute `brig version` - does that work?
or

```
$ cd $GOPATH
$ brig version
```

In either case, can you execute `brig`?

**Comment by thezaa** [comment]
oh it is showing :) .


Thanks

**Comment by radu-matei** [comment]
Glad it works now!
Closing, but feel free to reopen if you have additional questions.
