### ISSUE TITLE
Where is the source for brigade.sh?

### ISSUE THREAD

**Issue by zoidbergwill** [Azure/brigade#651]
The link in the repo discussion links to it, and then it links to the readme for documentation in its navbar instead of the docs site. Though I see in the web page it links to the actual docs.

https://brigade.sh/
https://github.com/azure/brigade#readme
https://azure.github.io/brigade/

**Comment by bacongobbler** [comment]
The source for brigade.sh lives in the docs folder: https://github.com/Azure/brigade/tree/master/docs

**Comment by zoidbergwill** [comment]
That looks like the source for https://azure.github.io/brigade/ and not https://brigade.sh/, though maybe we should change brigade.sh to redirect to the docs?

**Comment by bacongobbler** [comment]
I'm sorry, you're completely right. The source for brigade.sh is in a private repository and the source had not been made public. Is there anything in particular you'd like to know or change on the site?

**Comment by zoidbergwill** [comment]
No worries. I was wondering if my search for looking for the source was just failing me.

So the navbar link on brigade.sh should just link to the Azure docs URL, which is totally a nitpick tiny PR, but led me to wonder where it's source lives and whether it is maintained / should redirect to the Azure docs URL or not.
