### ISSUE TITLE
Disabling brigade-controller

### ISSUE THREAD

**Issue by cjhpaul** [Azure/brigade#662]
Before getting into the topic, I'd like to share a bit of my use case.
In a high level, I have a prototype service that creates both a brigade event and a worker (i.e., a secret and a pod) on an event, triggered by an app that is outside of the Kubernetes cluster. And I thought doing this would be more efficient, compared to going through brigade controller to provision workers.

I have 3 questions regarding the workflow I described above:
(1) Any insight/thoughts regarding the workflow above? i.e., having a custom controller, instead of using brigade-controller?
(2) Would it make sense to export a method used in brigade-controller to create a brigade worker (i.e., newWorkerPod in controller/handler.go)? so that it can be called in a custom controller as well.
(3) If (1) isn't a terrible idea, would it make sense to provide a helm option to disable it like brigade-gw and etc?

It would be appreciated if you can provide any feedback.

**Comment by vdice** [comment]
Hi @cjhpaul !  Although I don't yet have a similar use case to compare and/or advise here, in general I am in favor of further configurability to support unique use cases as long as the default/standard flow is unhindered.  To that end, if you've found a solution with one or more of 1,2 and 3 above, we'd be glad to take a look at a PR.

**Comment by cjhpaul** [comment]
@vdice Cool. I will try to come up with a solution. Thanks for your comment.

**Comment by cjhpaul** [comment]
Closed via #686 and #687 
Thank you for the reviews @vdice
