### ISSUE TITLE
Future of charts/brigade-project

### ISSUE THREAD

**Issue by kooba** [Azure/brigade#681]
Some of the documentation points to using Helm chart for creating new projects:
https://github.com/Azure/brigade/blob/master/charts/brigade-project/README.md
https://github.com/Azure/brigade/blob/master/docs/topics/developers.md
https://github.com/Azure/brigade/blob/master/docs/topics/github.md

And other parts mention that it will be deprecated with v1.0
https://github.com/Azure/brigade/blob/master/README.md#creating-a-new-project
https://github.com/Azure/brigade/blob/master/docs/topics/projects.md

Given that Brigade Project is just a Secret I would assume any means of creating that secret should be ok? We would like all of Brigade projects be scripted and checked in to Git and we already have a good way of encrypting k8s secrets that live in Git. Will there be some other artefacts created with `brig project create` command that would prevent us from being able to take care of managing project secrets ourselves?

Thank you for your help.

**Comment by technosophos** [comment]
Yeah, the `brig project create` will just create the secret. So it should be save to only create a secret.

**Comment by kooba** [comment]
Thank you @technosophos for clarification.
