### ISSUE TITLE
Dogfooding: api.brigade.sh seems to be broken

### ISSUE THREAD

**Issue by flynnduism** [Azure/brigade#691]
The `api.brigade.sh` server we use for testing projects isn't sending data to [our Kashti dashboard](https://azure.github.io/kashti/) anymore.

<img width="750" alt="screen shot 2018-11-15 at 4 57 28 pm" src="https://user-images.githubusercontent.com/686194/48591172-9342e100-e8f7-11e8-96a9-482341303046.png">

Slackbot error:

<img width="542" alt="screen shot 2018-11-15 at 4 52 28 pm" src="https://user-images.githubusercontent.com/686194/48591183-a2299380-e8f7-11e8-859f-f7463d05f1ab.png">

When I check the api endpoints via the browser, I see: `default backend - 404`

e.g. [https://api.brigade.sh/v1/projects](https://api.brigade.sh/v1/projects)

**Comment by vdice** [comment]
This is now fixed.
