### ISSUE TITLE
How to give brigade-worker more compute

### ISSUE THREAD

**Issue by iamnewspecies** [Azure/brigade#694]
I am using dind to build my projects. As it takes a lot of time for my project to build, I was thinking I can either set a a node affinity or make brigade.js ask for more resources for the dind deployment. But I was not able to see where I can do these changes. Is this feature supported? If yes can someone tell me where I should do this change?

**Comment by vdice** [comment]
@iamnewspecies there currently is a way to set resource requests on a given Job pod, though it looks like some documentation is missing.  On that note, check out following PR that both documents use of said `resourceRequests` as well as adding/documenting the ability to set resource limits: https://github.com/Azure/brigade/pull/693

**Comment by iamnewspecies** [comment]
Looks like this was merged less than a day ago. I have to build my image from master and put it in some registry.

**Comment by iamnewspecies** [comment]
We did the above mentioned change. But it is not quite helping. We also want to add ["Taints and Tolerations"](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) so that we can have a dedicated machine. Is there a way to mention this somewhere?

**Comment by iamnewspecies** [comment]
Found the solution. Jobhost and #693 helped.
