### ISSUE TITLE
Refactor: Build deletion optimization

### ISSUE THREAD

**Issue by vdice** [Azure/brigade#696]
A few potential refactoring opportunities around the build deletion logic (previously a part of brigade-vacuum) arose from a recent [PR](https://github.com/Azure/brigade/pull/695) (code in question not introduced by said PR).

See https://github.com/Azure/brigade/pull/695/files#r236771374 and https://github.com/Azure/brigade/pull/695/files#r236772397

Some of the logic could be worth revisiting and/or consolidation -- for instance, secret deletion if all build pods aren't deleted (perhaps because still pending/running, etc.)

**Comment by radu-matei** [comment]
Closed by #695
