### ISSUE TITLE
Clean up old builds

### ISSUE THREAD

**Issue by bacongobbler** [Azure/brigade#7]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-04-20 22:40:22_

----

Right now, each build creates at least one pod and one config map. Currently, for logging, these must persist "until the user is done with them" (e.g. until the logs are no longer relevant.

Really, we probably want to destroy the pod/configmap soon after it's run. But we can't really do this until we persist logging elsewhere

**Comment by bacongobbler** [comment]
**Comment by [jchauncey](https://github.com/jchauncey)**
_2017-04-21 21:52:28_

----

I would make this an option. That way people can inspect that state of a failed build and see what went wrong.

**Comment by bacongobbler** [comment]
**Comment by [bacongobbler](https://github.com/bacongobbler)**
_2017-07-04 23:22:55_

----

We could add a configurable option like BUILD_HISTORY_LIMIT that limits the number of pod/configmap sets that are available to view from the most recent builds. That along with a plugin system to push logs offshore would ideally be the best of both worlds.

**Comment by bacongobbler** [comment]
**Comment by [technosophos](https://github.com/technosophos)**
_2017-08-30 15:39:34_

----

At this point, we are setting a timestamp on secrets to indicate when it is safe to clean them up, but we still aren't automating anything.

**Comment by u2takey** [comment]
Should we add a cmd (delete/remove) on brigage-client? For now, adding a cmd : clearall, which clean all brigage-related resource, will be very helpful for developer.

**Comment by technosophos** [comment]
The idea to make this a feature of `brig` is a great idea.

**Comment by technosophos** [comment]
`brigade-vacuum` now does the time-based cleanup. Marking this as closed.
