### ISSUE TITLE
new job construction fails when the job name contains an uppercase letter. 

### ISSUE THREAD

**Issue by jpadif** [Azure/brigade#705]
I noticed that when you create a new job and assign the name using a constructor parameter it will fail if the name contains an uppercase letter. 

The error only says `Error: job name must be letters, numbers, and '-', and must not start or end with '-'` but it doesn't mention anything about uppercase letters.

This one will succeed:
```
var goodJob = new Job("jobaa", "alpine:3.4").tasks = ["echo job"];
```

But this one will fail:
```
var badJob = new Job("jobAa", "alpine:3.4").tasks = ["echo job"];
```

**Comment by jpadif** [comment]
It would be nice if we could change the error message so this is explained, I spent a while trying to figure out why that was happening.

**Comment by dgkanatsios** [comment]
closing as #709 has been merged
