### ISSUE TITLE
"status":"project not found"

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/brigade#711]
yaml file:

```
project: "4c74356b41/uuid"
repository: "github.com/4c74356b41/uuid"
cloneURL: "https://github.com/4c74356b41/uuid.git"
sharedSecret: "redacted"
github:
  token: "redacted"
```

Initial webhook worked, all the others are returning `{"status":"project not found"}`. 
```
helm status uuid
LAST DEPLOYED: Sat Dec  8 19:35:03 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                                                            AGE
brigade-xxx  3m
NOTES:
Your new Brigade project has been created.
This is a brigade project for github.com/4c74356b41/uuid
```

I dont understand what I'm doing wrong. This is all happening in AKS 1.11.5 and Azure cloud shell.

**Comment by dgkanatsios** [comment]
Can you do a ‘kubectl get secrets’ (you installed in the default namespace if I’m not mistaken) to see that the project definition (in the form of a Secret) is still there?

**Comment by 4c74356b41** [comment]
```
kubectl get secret
NAME                                                             TYPE                                  DATA      AGE
brigade-xxx   brigade.sh/project                    8         9h
```

@dgkanatsios

**Comment by dgkanatsios** [comment]
Is this the only secret? Are there no other ones, eg from the successful build you mentioned? 
I’d also try to see the logs of both controller and GitHub gateway, to find their names do a ‘kubectl get po’.
Gateway name should be something like ‘brigade-brigade-github-gw’ Whereas controller name should be ‘brigade-brigade-ctrl’

**Comment by 4c74356b41** [comment]
i did recreate the project a bunch of times with slightly different input parameters, so this is the only one that.

it appears it didnt create permissions for the brigade at all.

**Comment by 4c74356b41** [comment]
apparently install guide was written 3 years ago or something. rbac is the default for k8s long time ago, yet chart defaults to not using it. retarded? obviously.

solution:
```
helm install -n brigade brigade/brigade --set rbac.enabled=true
```
