### ISSUE TITLE
Create Azure/brigade-charts repo

### ISSUE THREAD

**Issue by vdice** [Azure/brigade#718]
As mentioned in the [Brigade 1.0.0 Meta ticket](https://github.com/Azure/brigade/issues/504):

 - [x] Create `Azure/brigade-charts` repository to hold all Brigade/related charts.  Current list:
    - brigade
    - brigade-project
    - kashti
    - brigade-github-app
    - brigade-k8s-gateway

 - [x] Serve charts (via `https://azure.github.io/brigade-charts`).  Requires https://github.com/Azure/brigade-charts/pull/1 (completed)

 - [x] Remove charts from originating repos, updating relevant docs in these repos mentioning this new GH repository, as well as helm chart repo url. **edit**: PRs issued; all depend on https://github.com/Azure/brigade-charts/pull/1 (completed)
    - https://github.com/Azure/kashti/pull/236 (completed)
    - https://github.com/Azure/brigade/pull/722 (completed)
    - https://github.com/Azure/brigade-github-app/pull/25 (completed)
    - https://github.com/Azure/brigade-k8s-gateway/pull/4 (completed)

**Comment by vdice** [comment]
@technosophos when you get a chance, could you double-check my list/work here?

**Comment by vdice** [comment]
Question: the breaking change here will be the new helm repository name, from the existing `https://azure.github.io/brigade` to the new `https://azure.github.io/brigade-charts` -- how best to alert users?

**Comment by rmb938** [comment]
@vdice Just an idea on how to alert users. We can update the NOTES.txt in each chart about the move. So if they install a chart from the old repo the helm install will show a message about the repo move.

It's not the best for automated install/upgrade systems but at least it's something.

**Comment by vdice** [comment]
@rmb938 that's a great idea -- it will certainly help.  So, perhaps, instead of removing charts from this repo now/soon, we can PR the disclaimers to each chart's NOTES.txt and keep those charts hosted (but not updated past most recent v0.19.0 release) for a bit longer.  (I would intend to just remove charts from kashti/brigade-github-app, etc., since those aren't actually hosted in the form of any repo yet.)

**Comment by vdice** [comment]
Brigade charts now hosted by new repo:
```
 $ helm repo add brigade-charts https://azure.github.io/brigade-charts
"brigade-charts" has been added to your repositories

 $ helm search brigade
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION
brigade-charts/brigade            	0.19.0       	v0.19.0    	Brigade provides event-driven scripting of Kubernetes pip...
brigade-charts/brigade-github-app 	0.1.1        	           	The Brigade GitHub App, an advanced gateway for GitHub
brigade-charts/brigade-k8s-gateway	0.1.0        	           	A Helm chart for Kubernetes
brigade-charts/brigade-project    	0.19.0       	v0.19.0    	Create a Brigade project
brigade/brigade                   	0.19.0       	v0.19.0    	Brigade provides event-driven scripting of Kubernetes pip...
brigade/brigade-project           	0.19.0       	v0.19.0    	Create a Brigade project
brigade-charts/kashti             	0.1.0        	           	A Helm chart for Kubernetes
```

**Comment by rmb938** [comment]
Awesome, I'm not sure how you guys release charts but typically to get the notes updated we would have to bump the chart versions, at least by a point release. 

So we would want something like the charts in this repo be 0.19.1 and stay at that version, then in the new charts repo have them be 0.19.2. Of course keeping the app version the same.

**Comment by radu-matei** [comment]
I'd also add deprecation notes for `brigade-project`, as we're going for the default experience for project creation to be with `brig`.

**Comment by vdice** [comment]
Done!
