### ISSUE TITLE
Add OwnerReferences to created Secrets and Pods

### ISSUE THREAD

**Issue by dgkanatsios** [Azure/brigade#724]
Wondering whether it would make sense for created resources to have OwnerReferences assigned, so that they are easily removed by the [Garbage Collection](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/) process. Specifically
- we create a Project -> a Project Secret (let's call it A) is Created
- we create a Build Secret - it has its OwnerReference set to A
- each Build will create a Worker Pod which will have OwnerReference set to the Build Secret
- Job Pod(s) will also have OwnerReference set to the Worker Pod

In this way, when we delete the Project Secret, all child/grandchild/etc. resources will be deleted. This may (or may not!) be the desired behavior in all cases, though.

Thoughts?

cc @technosophos @radu-matei

**Comment by radu-matei** [comment]
Closing in favor of #335 (linked your comment there) - feel free to comment there, or reopen if this is not the same work item.

Thanks!
