### ISSUE TITLE
Referencing and mounting Kubernetes secret and configmap to Kaniko container in brigade.js

### ISSUE THREAD

**Issue by inconbeo** [Azure/brigade#732]
Hi,

I am trying to run a Brigade Job which use Kaniko container to build and push image to AWS ECR. I need to reference kubernetes secret and configmap and mount those information to Kaniko container so that it can authenticate AWS ECR for push. I read the official documentation  which said I can reference secrets already in kubernetes cluster by using:

`myJob.env = {
  myOneOffSecret: "secret value",
  myConfigReference: {
    configMapKeyRef: {
      name: "my-configmap",
      key: "my-configmap-key"
    }
  },
  mySecretReference: {
    secretKeyRef: {
      name: "my-secret",
      key: "my-secret-key"
    }
  }
};`

My question is is it possible to reference kubernetes secrets and mount them to container specified in the brigade Job ?

**Comment by dgkanatsios** [comment]
Hi, maybe I'm not 100% getting what you want to do, have you checked the documentation about Secrets [here](https://azure.github.io/brigade/topics/secrets.html)? Basically, you can create your Secrets during Project creation and then use them in your JS via 
```javascript
j1.env = {
    "DB_PASSWORD": project.secrets.dbPassword
  }
```

**Comment by inconbeo** [comment]
Hi,

My question is if I already have secrets in Kubernetes cluster, is there any way that I mount the secrets to the container declared in the brigade.js file ? For example, mounting the secret volume to the container is possible if I create the pod with the yaml file. However, when I use brigade.js, it seems it does not provide interface for volume mounting ? Correct me if I am missing anything.

**Comment by vdice** [comment]
Hmmm, although I haven't used the functionality myself yet, it does seem the [pattern](https://github.com/Azure/brigade/blob/27ae89839cbaf898691c790dff2ad008d5ad2845/docs/topics/javascript.md#the-job-object) mentioned above would be a way to supply the job container's env with an env var pointing to a value derived from the secret/configmap reference (it appears the code [here]( https://github.com/Azure/brigade/blob/243aface99f3e908e26ead2ae66409289e4171a7/brigade-worker/src/k8s.ts#L311-L318) represents the mechanism to do so.)

@inconbeo have you tried this approach yet?

**Comment by inconbeo** [comment]
Hi, I did try that approach and it was not working. This is how do:

`one.env={
      
      mySecretReference: {
        
        secretKeyRef: {
          name: "aws-secret",
          key :"credentials",
          }
      },

      myConfigReference: {
        
        configMapKeyRef: {
          name: "docker-config",
          key: "config.json",
          }
      }
    }`

The only thing I am not sure is what should I put for "myConfigReference" and "mySecretReference". Or it is supposed to be like that.

**Comment by inconbeo** [comment]
hi,

Thanks for the example above, which is very helpful. I think it makes more sense to me now.
