### ISSUE TITLE
Feature request: read namespace from environment variable for brig

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#741]
If Brigade is deployed into a namespace other than `default`, from that point on, every `brig` command will have to be executed using the flag `--namespace <brigade-namespace>`.

Now most commands will fail in an obvious way because of the wrong namespace (such as `brig dashboard`, which doesn't find a Kashti pod and errors out) - but others will fail in a more subtle way - for example, creating a new project with `brig` without passing the namespace will create the project secret in the `default` namespace, which means builds for that project will not fire, because there is no secret for the project in your `<brigade-namespace>` namespace - and no logs will point you to why nothing is happening.

The easiest fix would be to set a default `<brigade-namespace>` for `brig` (that would then be used by other tools as well - for example `brigadeterm`, which needs the same flag if the namespace is different) - the obvious option would be to have an environment variable - `BRIGADE_NAMESPACE`, that if set, will change the `globalNamespace` variable across `brig`, so eliminating the need to pass the flag with each command.

In the case of multiple deployments of Brigade in the same cluster, in multiple namespaces, the flag will always take precedence (and the environment variable for the command can be passed before the command, or for the terminal session), thus not affecting this scenario.

Thoughts?

**Comment by dgkanatsios** [comment]
100% agree with the env proposal, seems to be the most elegant solution.
Apart from that, you also raise another interesting issue: I think that we would need a separate fix for `brig project create` so that it checks for the existence of Brigade controller before it creates the Secrets. WDYT?
