### ISSUE TITLE
Bring `brig project create` into parity with the chart

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#745]
For Brigade 0.15 and earlier, the way of creating new projects was by using the [`brigade-project` Helm chart](https://github.com/Azure/brigade-charts/tree/master/charts/brigade-project).

#534 added the an interactive prompt to new projects using the `brig` CLI, which has become the default way of creating projects.

We need to check what is missing from the CLI so that the two ways of creating projects are into parity - note that the projects created with the Helm chart remain compatible with Brigade.

related: #368

**Comment by radu-matei** [comment]
@itye-msft that would be fantastic!

Specifically, we have to make sure:

- all options from the chart are present in the new `brig` CLI
- flag things that are backwards incompatible from the new releases
- make sure that if someone creates a project using the chart (so v0.14) it still works even if the controller is at a newer version.

**Comment by vdice** [comment]
@itye-msft checking in to see if you've had a chance to start on this.  There aren't too many tickets left for the v1.0 milestone, so I was thought I'd check this one out if it hadn't been started.  Thanks!

**Comment by vdice** [comment]
@itye-msft no problem; thanks for checking in!  I grabbed a documentation ticket but will check back once that's up for PR.

**Comment by radu-matei** [comment]
As we've been using `brig` to create projects for the last I think 5 versions now, there doesn't seem to be anything left from the project chart that is not yet in `brig project create`.

Thanks, everyone!
