### ISSUE TITLE
Update GitHub gateway to new GitHub app

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#746]
This issue tracks the progress towards migrating to [the new Brigade GitHub App](https://github.com/azure/brigade-github-app):
  - [x] Disable GH gateway by default
  - [x] Add GitHub App support to the Github Gateway
  - [x] Add `check_suite` support to the Github Gateway
  - [x] ~~Delete the github.com/Azure/brigade-github-app (that will be replaced by this)~~ _edit (vdice): we've decided to keep this gateway in the form of a separate repo and chart_

related: #407, #225, #318

**Comment by vdice** [comment]
I started circling around this today, re-familiarizing myself with brigade-github-app and what it would look like to swap out Brigade's current/classic github gateway with the former.

However, before getting into the details of what this may look like -- though, I will mention, it _might_ just look like removing brigade's current gh-related files in `pkg/webhook` and swapping in those from brigade-github-app, as well as updating `brigade-github-gateway/cmd` similarly) -- I wanted to propse the following:

*If* the intention is to disable the GH gateway by default, as is the first bullet above, why not continue to host this (perhaps updated) gateway in [Azure/brigade-github-app](https://github.com/Azure/brigade-github-app) as well as continue to keep its separate Helm chart as exists today and just remove all GH gateway code from this repo itself?  Then, enabling becomes a matter of flipping a chart flag and thus including the brigade-github-app sub-chart into the release.  This would contribute to a more modular/composable Brigade setup, which seems to be a preferred way forward.

Thoughts?

**Comment by radu-matei** [comment]
Sure, that makes sense - however, would it make sense to migrate it over to `brigadecore`?

**Comment by vdice** [comment]
Pull requests are up with strategy mentioned above (remove older github gateway code/chart resources from Brigade in favor of opt-in approach to conditionally use brigade-github-app code/chart):

https://github.com/Azure/brigade/pull/797
https://github.com/Azure/brigade-charts/pull/22

PTAL @radu-matei @adamreese @technosophos

**Comment by vdice** [comment]
Both aforementioned PRs merged; closing.
