### ISSUE TITLE
Allowing secretKeyRef could be a security risk

### ISSUE THREAD

**Issue by rmb938** [Azure/brigade#750]
Allowing `secretKeyRef` in jobs can be considered a security risk and I would like the ability to disable this functionality and/or the ability to whitelist secret names.

Since service account tokens are kubernetes secrets a job can use any service account's token in the namespace. 

This is very bad as there may be service accounts in the namespace with elevated permissions that jobs should not have. (related issue #749)

**Comment by technosophos** [comment]
I would be totally in favor of being able to disable `secretKeyRef` at the project level.
