### ISSUE TITLE
CloudEvents support for generic gateway

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#764]
As #602 and #762 are getting worked on, one feature request we've been getting is support for [CloudEvents](https://cloudevents.io/).

Most of the work for this is already done in [the Brigade EventGrid gateway, which already has CloudEvents support](https://github.com/radu-matei/brigade-eventgrid-gateway/tree/master/pkg/cloudevents), but it would be nice for this to be supported out of the box by Brigade.

Are there any downsides to having support out of the  box?

cc @squillace

**Comment by squillace** [comment]
None but resources. As the code is a good way there, this could be completed, but not as a part of 1.0 blocking list.

**Comment by dgkanatsios** [comment]
Should we add another endpoint/URL on Generic Gateway that would accept CloudEvents?

**Comment by radu-matei** [comment]
Yeah, I think that should be the way to go here.
But it shouldn't block #762 from getting merged in its current state.

**Comment by dgkanatsios** [comment]
cool, I'm tempted to take a look :) Is there a go package that we can go get or just simple copy [this](https://github.com/radu-matei/brigade-eventgrid-gateway/blob/master/pkg/cloudevents/envelope.go)?

**Comment by dgkanatsios** [comment]
Cool, I'm tempted to take a look as soon as we merge #762 so we have a baseline

**Comment by radu-matei** [comment]
_As soon as we merge_ is now :joy: 
That sounds great, let me know if there is anything I can help with.

Thanks!

**Comment by dgkanatsios** [comment]
thank you, I'll take a look during the next days and probably come up with a rough design here, so we can discuss and then start implement

**Comment by radu-matei** [comment]
Closing as the design proposal for this moved to #798.
