### ISSUE TITLE
Custom per-project brigade.js location

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#765]
We need a way to specify a custom location for a `brigade.js` file within a repository.

We already have a [list of default locations](https://github.com/Azure/brigade/blob/master/brigade-worker/prestart.js#L5-L21) for the `brigade.js` file where the Brigade worker searches for it:

```
// Script locations in order of precedence.
const scripts = [
  // manual override for debugging
  process.env.BRIGADE_SCRIPT,

  // data mounted from event secret (e.g. brig run)
  "/etc/brigade/script",

  // checked out in repo
  "/vcs/brigade.js",

  // data mounted from project.DefaultScript
  "/etc/brigade-project/defaultScript",

  // mounted configmap named in brigade.sh/project.DefaultScriptName
  "/etc/brigade-default-script/brigade.js"
];
```

We need to add a prompt to `brig project create` for the custom script location within the repo (as advanced configuration for project), then read that value in the controller and set it as `$BRIGADE_SCRIPT` environment variable on the worker (we already do the same with build ID, commit ID, event provider, type and others). 

Then, when the worker starts, the first place it looks is already a custom location - however, we need to be careful when parsing it, as when creating the project, the script location should be relative to the repo root, while in the worker it has to be relative to `/vcs` (directory in the worker pod where Brigade clones the repo).

**Comment by rmb938** [comment]
Can use https://golang.org/pkg/path/filepath/#IsAbs to check if the path is absolute, if it is error.

**Comment by radu-matei** [comment]
In the end, we need to append whatever path supplied by the user to `/vcs/`, clearly specifying in the `brig` help and doc that the path you supply has to be relative to the repo root.

I guess we can use the Go package for separators (just in case someone supplies a Windows-formatted path), but since the Brigade worker is surely a Linux container... But yeah, the best practice is to use the cross platform path separators indeed.

**Comment by radu-matei** [comment]
Now this also plays well with #272 - as in - if you have a URL instead of a relative file path, the VCS sidecar  would get that file and the Brigade worker would use it.

Interesting to see how difficult that would be to implement, either as part of #766 or a follow-up.

cc @dgkanatsios

**Comment by dgkanatsios** [comment]
Hm, would it work in this way?
- Check if user input starts with http:// or https://
- if so, assign this directly to $BRIGADE_SCRIPT
- if not, check if relative path
- if it is relative path, assign “/vcs” + relative path to $BRIGADE_SCRIPT
- if not, show error

Thoughts?

**Comment by radu-matei** [comment]
The main issue here is going to be handling credentials for private repositories - and the VCS sidecar is already configured to handle those.

If we only set it to `$BRIGADE_SCRIPT`, it is the job of the Brigade worker to get the file, and I don't think it is the route we want to take.
