### ISSUE TITLE
brigade.sh: live demo shows nothing

### ISSUE THREAD

**Issue by squillace** [Azure/brigade#770]
https://azure.github.io/kashti/dashboard doesn't show anything for me. should it? it was the "live demo" link on https://brigade.sh.

**Comment by dgkanatsios** [comment]
I'm seeing this, maybe it was a temp issue?
<img width="884" alt="capture" src="https://user-images.githubusercontent.com/8256138/51045068-5c253f00-15cb-11e9-8d30-274413608328.PNG">

**Comment by radu-matei** [comment]
I also see all projects there.

**Comment by radu-matei** [comment]
It might have been a temporary issue with the API. 

Closing, but feel free to re-open if this is not a temporary issue.
Thanks!
