### ISSUE TITLE
LastBuild in ProjectBuildSummary is incorrect

### ISSUE THREAD

**Issue by lkt82** [Azure/brigade#780]
Hi 

The LastBuild property of ProjectBuildSummary is not the "last build", but only the last item in the list retuned from kubernetes. This behavior breaks the Kashti dashboard as almost all the projects that have failed builds are marked as RED even if there is a newer successful build.

You can even see this error in the Kashti  live demo 
https://azure.github.io/kashti/projects/brigade-fb9a3793086c96c531b5cea078a84782e32410914cd059a026b2ad

The first green build in newer and successful but the dashboard overview still makers the project as RED.

If possible the solution could be to sort the build list by creation date and not just pick the last build.

Output of `brig version`: v0.19.0-26-gb0574cf

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by radu-matei** [comment]
Closing, as this should be fixed by #781.
Feel free to re-open if the PR doesn't fully address your issue.

Thanks!
