### ISSUE TITLE
Default service account error

### ISSUE THREAD

**Issue by vdice** [Azure/brigade#808]
Testing against master (https://github.com/Azure/brigade/commit/5e2fbe537713e9196273d757eb3c3cbf46803979) in prep for cutting a beta `v1.0.0` release and hit the following.

I'm seeing pre-existing (default/unconfigured when it comes to service account) Brigade project builds error out with:
```
[brigade] Service Account brigade-worker does not match regex /brigade-worker/
```
It looks like the default service account is correct but that the regex matching needs fixing?

cc @rmb938

**Comment by radu-matei** [comment]
Well, it may be more straightforward than anticipated - https://github.com/Azure/brigade/blob/master/brigade-worker/src/index.ts#L81

**Comment by rmb938** [comment]
Huh I'm pretty sure I tested that :man_shrugging: 

@vdice Can you post the environment of the brigade worker as it shows in the pod yaml?

**Comment by radu-matei** [comment]
@rmb938 - it might have to do with:

```
if (!options.serviceAccount.match(`/${process.env.BRIGADE_SERVICE_ACCOUNT_REGEX}/`)) {
```

The slashes are become part of the string to be tested against.

**Comment by rmb938** [comment]
ah. Possibly, I didn't see that error when testing though which is strange.

**Comment by vdice** [comment]
Indeed, removed the slashes and no longer hit the error.

The worker env was:
```
      BRIGADE_SERVICE_ACCOUNT:        brigade-worker
...
      BRIGADE_SERVICE_ACCOUNT_REGEX:  brigade-worker
```
So, looked good there.

How about we merge the quick fix of removing the slashes and then follow-up with wrapping in unit tests as time permits?  (A new `index.ts` test file, perhaps?)

**Comment by rmb938** [comment]
Will do! I must have read the docs wrong on the match function.

**Comment by radu-matei** [comment]
Sure. @vdice  - I assume you have a patch for this?
I volunteer to add the tests.

**Comment by radu-matei** [comment]
That was fast, thanks!

**Comment by vdice** [comment]
Thanks for the quick response @rmb938 !
