### ISSUE TITLE
[docs] disable github pages website

### ISSUE THREAD

**Issue by flynnduism** [Azure/brigade#835]
Now that `docs.brigade.sh` is up and running, this repo's github pages site can be decommissioned. 

![screen shot 2019-03-08 at 10 09 59 am](https://user-images.githubusercontent.com/686194/54046892-7a9e5580-418a-11e9-9b11-e8ff2d66c1fb.png)

The changes have broken jekyll, triggering these errors when PRs are merged. We need an admin on the repo to be able to edit the settings.

**Comment by flynnduism** [comment]
@radu-matei has disabled github pages for this repo. Closing this now

**Comment by radu-matei** [comment]
Great, assign the blame to me, @flynnduism 😂

**Comment by flynnduism** [comment]
nothing to see here

![https://media.giphy.com/media/ScmA88oVeD78aEpd2O/giphy.gif](https://media.giphy.com/media/ScmA88oVeD78aEpd2O/giphy.gif)
