### ISSUE TITLE
questions about git-sidecar/ storage/ plugin

### ISSUE THREAD

**Issue by u2takey** [Azure/brigade#84]
1. Like drone, "git clone" can be a single step (job) in a build, why use it as a "side-car". (in fact, as far as i known, side-car is used to refer containers in pod spec, not in "init-containers")
2. storage/cache may not be used in the whole build, why create it in the first step? Will it be better as a "lazy initialization" when it is actually requested? 
3. pod/pvc creation may be more readable using a "template-rendering" system like helm (use something like golang's "text/template").
4. is there a plan to introduce a plugin system (maybe we can implemented it as a js library, which utilizes 'jod' for its really action), which can be very useful.

**Comment by technosophos** [comment]
1. Our initial assumption was that most people would want the VCS tree available, and it's sometimes hard to do right. So we made that the default behavior, and added a Job flag to disable it.

We could re-evaluate that assumption. What are your thoughts?

2. We committed a change yesterday to change storage to off-by-default. Cache is already off-by-default. Depending on how that works, we might be able to even delay the initial PVC creation until something requests having it.

I had originally thought that the common use case would be to share files from container to container. But the early usage patterns suggest that this is not the case. So disabling will greatly increase speed and actually make the platform more generic. So we changed the default.

3. Maybe. We hadn't thought of that. You are thinking mainly in the Brigade Controller, right?

4. I have experimented with a few ways of allow `require` to access a custom library, but we decided to not implement that yet. If you have some ideas about patterns for that, let us know.

I could imagine being able to load JS libraries that are stored in the VCS clone. That might make it easy to write supporting JS code that could be used inside of a `brigade.js`. The trade-off is that if we allow it, we are making the system more complicated. But that may be okay.

**Comment by u2takey** [comment]
@technosophos thanks so much for your kind and detailed response. And also thanks for open-source brigade. Brigade's design is so nice and it can be a very good supplement for k8s's "Job/CronJob" as a general pipeline system for complicated workflow. 
For 1~3, i have no questions now, your design is reasonable. 
For 4, maybe we can first supply with "official plugins" in brigade-worker's node-modules, so that these plugins could be used inside `brigade.js` (use this pattern we may need to update brigade-worker's image when plugins update).

**Comment by technosophos** [comment]
I like that idea for 4. That is a reasonable way to start. We can be more flexible later if needed.
