### ISSUE TITLE
Events generated by the generic gateway should be consistent with their path

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#842]
The event type generated by the generic gateway are `cloudevent` and `simpleevent`. This is rather confusing, given that the paths for the two are pluralized.

This can result in a lot of confusion.

```
const { events, Job } = require("brigadier");

events.on("simpleevent", (e, p) => {  // handler for a SimpleEvent
  var echo = new Job("echosimpleevent", "alpine:3.8");
  echo.tasks = [
    "echo Project " + p.name,
    "echo event type: $EVENT_TYPE"
  ];
  echo.env = {
    "EVENT_TYPE": e.type
  };
  echo.run();
});

events.on("cloudevent", (e, p) => { // handler for a CloudEvent
  var echo = new Job("echocloudevent", "alpine:3.8");
  echo.tasks = [
    "echo Project " + p.name,
    "echo event type: $EVENT_TYPE"
  ];
  echo.env = {
    "EVENT_TYPE": e.type
  };
  echo.run();
});
```

**Comment by dgkanatsios** [comment]
We generally use singular words on event types, no?
E.g. https://github.com/Azure/brigade/blob/master/pkg/webhook/dockerhub.go#L77 "image_push"
https://github.com/Azure/brigade-github-app/blob/master/pkg/webhook/github.go#L67 also singular as well

**Comment by radu-matei** [comment]
That also makes sense...

Can we at least have another notice in the docs about this?
